### ISSUE TITLE
Another way to show the chart using pure DOM and CSS

### ISSUE THREAD

**Issue by Tobyee** [dabeng/OrgChart#1]
Refer to
http://thecodeplayer.com/walkthrough/css3-family-tree

**Comment by dabeng** [comment]
Cool chart! It makes use of nested <ul>. Maybe this is the new feature for next version of OrgChart.

**Comment by dabeng** [comment]
Thanks a lot for @Tobyee 's advice, we have provided ul datasource from version 0.9.9

**Comment by neights** [comment]
Hello, can you generate a static, unable to click and flex architecture? How do

**Comment by jigarce** [comment]
How do i add <div class="content">department manager</div> in UL as source?

**Comment by jigarce** [comment]
How to add Content in <UL> as source Method , We just have Name in <LI> like Name / Production Manager

**Comment by k3youmin** [comment]
How to can I install this js in my laravel project?

**Comment by AbhishekGNG** [comment]
> Refer to
> http://thecodeplayer.com/walkthrough/css3-family-tree

Great work!!, solved the big problem into small pieces, I did some updates,  Some how I managed to add/append dynamic data to multiple level, but the only problem I'm facing is dynamic width of the structure, it breaks down to every level when the tree overflows parent element.

Any suggestion or Solution?

**Comment by tobyee** [comment]
@AbhishekGNG 
These is a very simple solution, change `li` element from `float` to `table-cell`
```css
.tree li {
   display: table-cell;
   /* other properties*/
}
```
