### ISSUE TITLE
Adjust node width

### ISSUE THREAD

**Issue by dilyan-ivanov** [dabeng/OrgChart#100]
Hi all!

How can I change node width, without causing problems to structure?

**Comment by suvarov** [comment]
Do you need fixed width change for all nodes?
if so, go to jquery.orgchart.css and update .orgchart .node {width: 120px } to a desired value

**Comment by dilyan-ivanov** [comment]
Thank you for fast reply @suvarov!
Yes I need fixed width for all nodes. I already tried to update .orgchart .node, but without success.

**Comment by dilyan-ivanov** [comment]
I find a solution! Thank you, @suvarov

**Comment by skapin** [comment]
@dilyan-ivanov  thanks for sharing ..... ....

**Comment by fathiabdulrahim** [comment]
@dilyan-ivanov may i know what is the solution
