### ISSUE TITLE
destroy and/or update

### ISSUE THREAD

**Issue by manuel-84** [dabeng/OrgChart#102]
how do I destroy an orgChart or I update the data?

**Comment by dabeng** [comment]
Hi @manuel-84 , you can use the following statement to destroy the whole orgchart:
`$(#chart-container).empty();`
You know, in generally, orgchart is just a nested table structure.

**Comment by dabeng** [comment]
As for how to update the data of node, you just need to embed input region into the node with callback createNode, after user clicks the "save" button , one side, you update the UI with saved results, on the other side, you send a ajax request to notice the backend that some datao of the node has been changed.

**Comment by manuel-84** [comment]
I mean how to update the whole graph passing updated data to render
