### ISSUE TITLE
in-place editing of nodes

### ISSUE THREAD

**Issue by dwfee** [dabeng/OrgChart#105]
is it possible to allow users to edit nodes in-place, e.g. onclick make placeholder text disappear and start writing whatever you want?

**Comment by dabeng** [comment]
Of course, you can modify the internal structure by option createNode. Just put the code snippets of edit-box into createNode callback.

**Comment by Zmove** [comment]
@dwfee did you implement this with success ? I'm interested with inline editing (some icons on node to add sibiliing, children, edit current nodes etc....) the actual example with a form on the bottom of the chart is not really good in term of UI (and you can't edit a selected node)

**Comment by dextersolar** [comment]
any updates?
