### ISSUE TITLE
Not working with IE8

### ISSUE THREAD

**Issue by magigedaniel** [dabeng/OrgChart#106]
First of all, thanks for such a great effort that you put in JS and created a wonderful Orgaschart.... Anyway have tried to work with it in IE 8 without success. Here is the error?

> Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E)
Timestamp: Tue, 22 Nov 2016 12:45:11 UTC

Message: Script error
Line: 0
Char: 0
Code: 0
URI: https://code.jquery.com/jquery-3.1.0.min.js

Message: Script error
Line: 0
Char: 0
Code: 0
URI: https://cdn.rawgit.com/niklasvh/html2canvas/master/dist/html2canvas.min.js

Message: 'jQuery' is undefined
Line: 25
Char: 5
Code: 0
URI: http://dabeng.github.io/OrgChart/js/jquery.orgchart.js

Message: 'jQuery' is undefined
Line: 3
Char: 1
Code: 0
URI: http://dabeng.github.io/OrgChart/export-orgchart/scripts.js

>

**Comment by muhammad-raja** [comment]
One of many reason could be because jQuery 3 doesn't supports IE-8.
Reference: https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/

I am not confident but you may try same library without JQuery,
https://github.com/dabeng/OrgChart.js
