### ISSUE TITLE
Are multiple root nodes possible ?

### ISSUE THREAD

**Issue by similiarforce** [dabeng/OrgChart#109]
I believe at the moment we can't provide array of object as input e.g. if we have a organization with 2 CEOs :).

Is there anyway to support this ?

Thank you

**Comment by dabeng** [comment]
Hi @similiarforce , can you guarantee every child node has only one parent node in your orgchart?

**Comment by similiarforce** [comment]
Hi @dabeng, thank you are quick reply.

Yes, you are right, these root/parent nodes will have only there own children, they won't going to share 
children.

My structure would look something like this,

![image](https://cloud.githubusercontent.com/assets/23716657/20594557/963aada4-b22e-11e6-96fc-4b6a0e7fce05.png)


As you can see there are 4 root nodes not just 1 :)

Many Thanks

**Comment by dabeng** [comment]
Hi @similiarforce , you just need a little trick.
![issues-109](https://cloud.githubusercontent.com/assets/5689075/20618462/bfb3e9e4-b2b4-11e6-8a96-46ca92ac8207.png)

**Comment by similiarforce** [comment]
Hi @dabeng 

Yes you are right, I was just checking if there is anything already in the library, by the way to make it work this way, I am adding a virtual root to my data as well.

Thanks for looking into it :)

**Comment by skapin** [comment]
How can I hide root element easily ?

**Comment by minvalencia** [comment]
How can I achieve this 
![image](https://user-images.githubusercontent.com/15870174/179170648-020d2741-0275-44d4-8a18-d91302b80dcf.png)
