### ISSUE TITLE
not compatible to jquery-1.10

### ISSUE THREAD

**Issue by jianyi0115** [dabeng/OrgChart#114]
I use jquery-1.10 and there is js null ref js error on method createNode method

 $.each(nodeData.children, function (index, child) {
      child.parentId = nodeData.id;
      });

//here for no children node,the nodeData.children is null, Jquery throw a null reference exception.
I changed the code:

      nodeData.children && $.each(nodeData.children, function (index, child) {
      child.parentId = nodeData.id;
      });

**Comment by dabeng** [comment]
sorry @jianyi0115, orgchart plugin is based on jquery 3, we don't plan to support the old jquery versions.

**Comment by KingGeneral** [comment]
yes, this one not working with 1.11 or even jquery 2. thx for clarify

i hope it supported in future
![image](https://cloud.githubusercontent.com/assets/9468485/24026822/57962882-0af6-11e7-9307-0589dee716d0.png)
