### ISSUE TITLE
How build a datascourse with mysl/php datas

### ISSUE THREAD

**Issue by bcaspar** [dabeng/OrgChart#117]
I can't find a function for create a datasource like your exemple:
```js
'name': 'Emmanuel Perrotin',
'title': 'General manager',
'children': [
  { 'name': 'Bo Miao', 'title': 'department manager' },
  { 'name': 'Su Miao', 'title': 'department manager',
	'children': [
	  { 'name': 'Tie Hua', 'title': 'senior engineer' },
	  { 'name': 'Hei Hei', 'title': 'senior engineer',
		'children': [
		  { 'name': 'Pang Pang', 'title': 'engineer' },
		  { 'name': 'Xiang Xiang', 'title': 'UE engineer' }
		]
	  }
	]
  },
  { 'name': 'Yu Jie', 'title': 'department manager' },
  { 'name': 'Yu Li', 'title': 'department manager' },
  { 'name': 'Hong Miao', 'title': 'department manager' },
  { 'name': 'Yu Wei', 'title': 'department manager' },
  { 'name': 'Chun Miao', 'title': 'department manager' },
  { 'name': 'Yu Tie', 'title': 'department manager' }
]
```
Thank you.

brice

**Comment by dabeng** [comment]
Sorry @bcaspar , construct the json datasource is your own task, plugin orgchart won't provide this feature. Please refer to https://github.com/dabeng/OrgChart#structure-of-datasource.

**Comment by bcaspar** [comment]
Thanks, I found this one. Works fine for me.

function structure($parent, $niveau, $array) {
    $html = "";
    $niveau_precedent = 0;
    if (!$niveau and !$niveau_precedent) $html .= ""; 
    foreach ($array as $noeud) {
		if ($parent == $noeud['parent_id']) {
            if ($niveau_precedent < $niveau) $html .= ",\n'children': [\n";
            $html .= "{'id':'".$noeud['categorie_id']."', 'name':'". $noeud['nom_categorie']."', 'title':'". $noeud['photo']."<br />".$noeud['role']."'";
            $niveau_precedent = $niveau;
            $html .= structure($noeud['categorie_id'], ($niveau + 1), $array);
		}
    }
    if (($niveau_precedent == $niveau) && ($niveau_precedent != 0)) $html .= "]\n},\n";
    else if ($niveau_precedent == $niveau) $html .= "\n";
    else $html .= "},\n";
    return $html;
}

$array = datas.

Brice

**Comment by dabeng** [comment]
Sorry @bcaspar , I can't fully understand your structure() method, but I know constructing json datasoure by concontinating string is not a good practice.
