### ISSUE TITLE
Export-Orgchart does not work in IE

### ISSUE THREAD

**Issue by renzedu** [dabeng/OrgChart#118]
Export Functionality does not work in IE

http://dabeng.github.io/OrgChart/export-orgchart/

**Comment by dabeng** [comment]
Hi @renzedu , which version of IE do you use?

**Comment by renzedu** [comment]
IE11 - Please find a screenshot below. 
![screenshot](https://cloud.githubusercontent.com/assets/9271301/21401595/f4e4fb5c-c782-11e6-8894-aac7381a5fee.jpg)

**Comment by dabeng** [comment]
Thank you @renzedu , I got the same error. So sorry I didn't do a comprehensive testing on IE.

**Comment by rjasica** [comment]
@renzedu I created some hotfix for this issue. It also works for Edge. 
For IE, It might require to include "es6-promise.auto.js" in your project(required by html2canvas).

**Comment by dabeng** [comment]
It's correct. l'll merge rjasica's PR as soon as possible.
