### ISSUE TITLE
try to do something?

### ISSUE THREAD

**Issue by imman731** [dabeng/OrgChart#119]
Hi, I have question.
How can i do something or Is it possible to support function as below?
1. line with onclick event
2. relationship (add line) between tree and tree.

**Comment by dabeng** [comment]
Hi @imman731 , I got your points. However, I‘m sorry to say that lines in orgchart are just composition of borders of a series of tds which are just in charge of reflecting the hierarchical relationship between nodes. Current codes couldn't fulfill the two requirements you put forward.

**Comment by imman731** [comment]
Hi @dabeng , Thank you for your reply and don't feel sorry about that. It's a good composition !
