### ISSUE TITLE
Panning out of bounds when not in L2R direction.

### ISSUE THREAD

**Issue by St1fle** [dabeng/OrgChart#121]
Hello @dabeng 

I tried to update the last issue that got closed but I got no response there so I am reopening this ticket and copy pasting my reply so you can see my problem.

I will try to show you what my problem is with pictures.

A horizontal layout has this problem (this is what it looks like when we load the page, because the chart is so huge):
![Horizontal Graph](http://i.imgur.com/CqeR9og.jpg)

It forces the user to zoom out many times back and it becomes very small, another problem we have (and we had to disable zoom because of this) is that when we zoomed in the graph we were also scrolling on the page so people were struggling with controlling the zoom, is there something on my side that I can change to fix this?

So we decided to use a vertical layout like this, which looked great by the way:
![VerticalGraph](http://i.imgur.com/PkX9JfN.jpg)

But this vertical layout when you drag it, it isn't "locked" to the chart space, it can be dragged _anywhere_ in the page. This is the problem I was trying to point out (notice how in the last picture the chart is over the sidebar on the left, instead of dragging around the chart space).

Horizontal cuts user davideferreira (this is what we want):
![VerticalGraph](http://i.imgur.com/13uXzYK.jpg)

But vertical layout overflows anywhere on the screen:
![VerticalGraph](http://i.imgur.com/cYlPVQW.jpg)

I hope this explains my situation better and I am sorry for not being very explicative in the first place.

**Comment by dabeng** [comment]
hi @St1file, take it easy, I'll take the time to fix the issue you mentioned

**Comment by dabeng** [comment]
additionally, theme and layout of your web app is very cool!

**Comment by St1fle** [comment]
Hello @dabeng !

I am sorry, I thought because you closed the issue you were no longer getting notifications from that ticket so I assumed I had to open another one, I apologize for this mistake on my part.

I am glad you liked it! The company owners were very pleased with the aesthetics and functionality of the graph and, while we are working on another areas of the business right now, we would like to come back to the graphs to do more advanced functionalities (for example selecting a username from a dropdown and having the graph focus on that user automatically, we will do this later ourselves). But first we need this issue fixed as it is causing problems to our users when using the graph.

**Comment by dabeng** [comment]
Hi @St1fle , please review this **[demo](http://codepen.io/dabeng/pen/RRwZwy/)**. I enable option "pan", but when i pan the chart, it doesn't go out of boundary. I guess there is something wrong inside the css sytles of your chart-container.

**Comment by dabeng** [comment]
In consideration of your scenario, I recommend you use [hybrid(horizontal + vertical) chart](http://dabeng.github.io/OrgChart/vertical-depth/)

**Comment by St1fle** [comment]
@dabeng thank you for your contribution again. We were able to solve the problem thanks to you. So apparently we needed to wrap the graph in a div with proper CSS. 

I will show you, before we had this:

                <div class="tabbable">
                    
                    <ul class="nav nav-tabs" id="teamTab">
                        <li class="active">
                            <a href="#genealogy" data-toggle="tab">Genealogy</a>
                        </li>
                    </ul>

                    
                    <div class="tab-content">
                        <div class="gap gap-small"></div>
                        <div class="tab-pane fade in active" id="genealogy">
                        </div>
                    </div>
                </div>

And we were building the graph on the tab-pane with id "genealogy" and because this tab-pane didn't have a width/height with a position: relative the graph itself wasn't being constricted to the tab-pane area. After your demo I realized that if I wrap the graph around a div in the tab-pane like so:

                        <div class="tab-pane fade in active" id="genealogy">
                            <div id="chart-container"></div>
                        </div>

And give it proper CSS:

#chart-container {
    position: relative;
    display: inline-block;
    top: 10px;
    left: 10px;
    height: 420px;
    width: calc(100% - 24px);
    border: 2px dashed #aaa;
    border-radius: 5px;
    overflow: auto;
    text-align: center;
}

Everything works fine again. I can't really explain but I think if you set the JS to append to an ID element which doesn't have the proper position, width and height the graph flows around in this L2R direction. I believe this is an error on our part and not of the graph so thank you so much for taking the time to provide us with this demo as it truly gave us a solution.

I wish you all the best!

**Comment by SSchindi** [comment]
@St1fle Had the same problem... The css-class for #chart-container fixed it, thank you so much!
