### ISSUE TITLE
How to used 'toggleSiblingsResp'?

### ISSUE THREAD

**Issue by CrazyBye1988** [dabeng/OrgChart#123]
Hi @dabeng 
    I set the 'false' value for properties ,but can not see any effect. The siblings was still can show or hide on the chart.It was a bug ? Or maby I has a wrong way to used?

**Comment by dabeng** [comment]
Enable "toggleSiblingsResp", just allow uses to show/hide the right/left side sibling nodes every time users click the right/left arrow of a node.
