### ISSUE TITLE
List inside an element

### ISSUE THREAD

**Issue by DaCuriousCase** [dabeng/OrgChart#124]
Hello,

The features provided by this plugin are quite fascinating and useful and the primary reason i choose to use this.
But i came across a problem - When we want an element in the chart to contain a list, that isn't allowed also i tried to use pre,label,p,span etc but they would just break down as child elements of their parent.

Please provide me with some insight on this topic .
(I have provided a sample of the code and the result)

Thanks,
Ram.

![image](https://cloud.githubusercontent.com/assets/24771377/21476177/8b0adbde-cb5b-11e6-8644-8b807a1bf7e0.png)
![image](https://cloud.githubusercontent.com/assets/24771377/21476190/b4209f18-cb5b-11e6-976b-35388b40ce2c.png)

**Comment by dabeng** [comment]
Hi @DaCuriousCase , I guess you used the ul datasource, right ?

In fact, when you choose to build up orgchart with ul datasource, plugin orgchart will use the hierarchy of ul & li to construct the hierarchy of organization chart. So I recommend you use json datasource and use callback "creteNode" to append the list you mentioned above.
