### ISSUE TITLE
Canvas size on "I wanna customize the structure of node"

### ISSUE THREAD

**Issue by bryanrscott** [dabeng/OrgChart#126]
Hi

When combining examples
a) "I wanna customize the structure of node" http://dabeng.github.io/OrgChart/option-createNode/ 
and
b) http://dabeng.github.io/OrgChart/export-orgchart/

a small corner case arises.   If you bring up the secondary menu (to display the user icon) on the org chart element on the right most, the canvas does not expand and the when you print the use image is outputted.

**Comment by dabeng** [comment]
Hi @bryanrscott , I got your point, but you know that plugin orgchart use html2canvas to export the hierarchy, however, if the stucture of orgchart is too complex, then the htlm2canvas can not handle it, I' m afraid I can` t help you with that cause it;s out of orchart's power.

**Comment by dabeng** [comment]
html2canvas can not export the within the target DOM.
