### ISSUE TITLE
Namespace css correctly

### ISSUE THREAD

**Issue by CUnknown** [dabeng/OrgChart#13]
Please, do not use css which is not namespaced correctly. For example: I see that you define a .hidden class with a display: none; In my projects, I could also have used a hidden class and this will interfere with the hidden class you use for this plugin...

Also .node, .slide-up, .slide-down are also not namespaced. If you agree, I could make a PR.

**Comment by dabeng** [comment]
Thanks a lot for your good advice. Based on your suggestion, I pushed v1.0.1.6 :blush:
