### ISSUE TITLE
Export OrgChar to pdf

### ISSUE THREAD

**Issue by SuperRooo** [dabeng/OrgChart#134]
How this  OrgChar can export as a pdf file. It would be really awesome if its export as pdf too.

**Comment by dabeng** [comment]
Hi @SuperRooo , you can use version 1.3.2 to export the ortchart as a pdf document. Specifically, you  just need to append a setting `exportFileextension: 'pdf'`

**Comment by dabeng** [comment]
Do't forget to introduce [jsPDF](https://github.com/MrRio/jsPDF) firstly. :blush:

**Comment by erb4f1dotama** [comment]
how to define html2canvas and jspdf in jquery.orgchart.js? Because when i tried click button export, i got error "html2canvas is not defined"
