### ISSUE TITLE
Class conflict for ".spinner"

### ISSUE THREAD

**Issue by johnomorales** [dabeng/OrgChart#139]
Another plugin of mine, is using the class ".spinner" (common class name)

Perhaps you can change it to a more specific type like ".orgchart_spinner" to avoid conflict.

**Comment by dabeng** [comment]
Hi @johnomorales , in jquery.orgchart.css file, I have used classname "orgchart" to prevent class confilct, for example on line 126:
```css
.orgchart>.spinner {
```
If you don't override the above css code snippets, you won't get conflict error.

**Comment by johnomorales** [comment]
the problem is that i have another css plugin that uses

.spinner class

https://github.com/tobiasahlin/SpinKit

**Comment by dabeng** [comment]
Hi @johnomorales , I have to admit that SpinKit is very cool, you can just replace the style settings of orgchart spinner with SpinKit spinner, it's up to you.

**Comment by johnomorales** [comment]
Thanks for the feedback, great plugin BTW and keep up the good work!.
