### ISSUE TITLE
How to add All siblings to Left Only or Right Only

### ISSUE THREAD

**Issue by tsrinfotech** [dabeng/OrgChart#14]
when i am viewing my siblings,
right now my current node is positioning to center.
But I would like to view all my siblings to right side or left side according to the need.

**Comment by dabeng** [comment]
You can enable option "draggable" and then drag the sibling nodes to right side/left side. It's up to you.
![5](https://cloud.githubusercontent.com/assets/5689075/15134814/2abd1e9e-1635-11e6-8d62-fb33afdfcb7d.gif)
