### ISSUE TITLE
hideChildren not working properly

### ISSUE THREAD

**Issue by supermafete** [dabeng/OrgChart#148]
Hi there,

I have an orgchart with three node classes (department, job and worker). Departments can be childs of other departments. Initially I just want to show departments and jobs, letting the user choose to expand jobs and see workers.

I'm doing the following to collapse all '.job' nodes:

```
 var job_elements = $('#chart-container').find('.job');
 $('#chart-container').orgchart('hideChildren',job_elements);
```
Attached my tree and screenshot.

<img width="1273" alt="captura de pantalla 2017-01-27 a las 19 37 14" src="https://cloud.githubusercontent.com/assets/1788411/22383051/8110e8ae-e4c8-11e6-8313-33c7642438ac.png">

[orgchart-tree.txt](https://github.com/dabeng/OrgChart/files/736019/orgchart-tree.txt)

**Comment by dabeng** [comment]
Hi @supermafete , I have released a new version which includes new option "collapsed" for datasource that can help uses to collapse some nodes by default. Besides, the method hideChilden() is based on single node rather than multiple nodes. Please refer to [Demo](http://dabeng.github.io/OrgChart/default-collapsed/)

**Comment by dabeng** [comment]
It's modified version of datasource.
[orgchart-tree.txt](https://github.com/dabeng/OrgChart/files/738093/orgchart-tree.txt)

**Comment by supermafete** [comment]
Hi Dabeng! 

Many thanks for the patch. It works almost perfectly :) 

Only one matter. After open a pre-collapsed node, then we can't collapse it again. Although current solution is acceptable for my project, it would be perfect if we can collapse opened pre-collapsed nodes.

Regards.

**Comment by dabeng** [comment]
Hi @supermafete , I can't find the bug you mentioned above. Could you demonstrate your issue on this [Demo](http://codepen.io/dabeng/pen/vgpeEy) based on the datasource you provided.

**Comment by supermafete** [comment]
Hi again!

No problem with your tree, but in this demo you can see the problem in nodes named “Puesto”. Try to expand and collapse. BTW, I didn’t change the tree creation process, so I have no idea what is buggy here.

Note that animations wouldn’t work if you try to expand any “Puesto”, and then you couldn’t collapse it again, neither “Puesto” or any node at all.

**Comment by dabeng** [comment]
Hi my friend @supermafete , you missed className "slide-up" in datasource, you can find it on my [Demo](http://codepen.io/dabeng/pen/vgpeEy) :blush:

**Comment by supermafete** [comment]
Oh! That's true! It's working perfectly now. Many thanks @dabeng ;)
