### ISSUE TITLE
How to show tooltip?

### ISSUE THREAD

**Issue by jeevasusej** [dabeng/OrgChart#149]
If we give longer texts, then texts will be hidden in the name and title.
How to show the tooltip for the texts?

**Comment by dabeng** [comment]
hi @jeevasusej, I suggest you to fix this issue by enlarging the node rather than adding tooltip

**Comment by sandip8600** [comment]
@dabeng  how do I enlarge node ??

**Comment by ghuang0207** [comment]
To sandip8600:  use F12 to find the html element and change its css style. (overwrite the styles).

**Comment by krosoftware** [comment]
Hello
Thank you for great piece of software.
How to solve problem when one node have 10 words of additional text and other node 2 words or nothing? I also think that tooltip will be better idea..
Thank you for consideration.

**Comment by krosoftware** [comment]
Any news regarding tooltip, please?

**Comment by pc1990** [comment]
Hello
Solution add style to resize
<style>
    .orgchart .node {
        width: auto;
    }

        .orgchart .node .title {
            height: 20px;
            position: relative;
            width: 200px;
        }

        .orgchart .node .content {
            height: 40px;
            line-height: 3;
        }
</style>

**Comment by krosoftware** [comment]
Hello
thank you for your idea, it is OK for some cases but not for me.
Currently I'm using other orgChart component (http://capricasoftware.co.uk/#/projects/orgchart/demos) where I can add Title="any HTML content" because I need 4,5 (or more) lines of text for some nodes.
On that way, all my orgchart fields have normal size and only some have Note text (when user move with mouse over them).

**Comment by doarsal** [comment]
http://creappti.com/scripts/orgChart/

**Comment by jnunderwood** [comment]
Here is an example of adding a tooltip for the 'content' section of a node:

```
$('#orgchart-container').orgchart({
    // other orgchart settings here...
    'createNode': function($node, data) {
        $node.on('mouseover', function(event) {
            var target = event.target;
            if ($(target).is('.content') && !$(target).attr('title')) {
                if ($(target).prop('scrollWidth') > $(target).prop('clientWidth')) {
                    $(target).attr('title', $(target).html());
                    // $(document).tooltip();  // jquery-ui tooltip
                }
            }
        });
    }
});
```
This only adds a tooltip if it hasn't been added before and only if the content is too long to display. It relies on the standard HTML `title` attribute. You can also uncomment the `$(document).tooltip()` line if you want to use `jquery-ui` tooltips.
