### ISSUE TITLE
can we have multiple org charts ?

### ISSUE THREAD

**Issue by smbasha47** [dabeng/OrgChart#15]
can we have multiple org charts ?

**Comment by dabeng** [comment]
Sorry, I can't get your point, could you explain your idea clearly?

**Comment by smbasha47** [comment]
in your example you have only one root node right. I want multiple root nodes and i want to drag and drop across the nodes

**Comment by dabeng** [comment]
Sorry smbasha47, currently, we haven't assigned high priority on  "multiple roots" feature.
