### ISSUE TITLE
Dynamically change the whole datasource

### ISSUE THREAD

**Issue by carloborsoi** [dabeng/OrgChart#150]
Hi,

 I would like to update the orgChart data using a complete data source, from a ajax server GET.
 
 The ideia is to remove the old one and put another complete data.

Thanks !

**Comment by dabeng** [comment]
Hi @carloborsoi , I believe this [Demo](http://dabeng.github.io/OrgChart/multiple-layers/) is what you need.

**Comment by dabeng** [comment]
Hi @carloborsoi , I'm glad to tell you since verison 2.0.0, you can use init() method to finish the task you mentioned above. For details, you can play around this **[Demo](http://dabeng.github.io/OrgChart/reload-data/)**.
