### ISSUE TITLE
Export format was broken

### ISSUE THREAD

**Issue by sayamkrai** [dabeng/OrgChart#152]
i have tried to export a org chart, but the picture result was broken not match with the UI before export.
From an example link:

http://dabeng.github.io/OrgChart/export-orgchart/

After i clicked a "Export" button i got a below result.
![myorgchart](https://cloud.githubusercontent.com/assets/8347502/22861063/0eb0570a-f142-11e6-8d80-0287cd9068f7.png)

FYI, this happen on Chrome and Firefox, the IE work correctly.

**Comment by dabeng** [comment]
Hi @sayamkrai , what's your Chrome version?

**Comment by sayamkrai** [comment]
@dabeng , my chrome version is "56.0.2924.87 (64 bit)"

However, I have tried to reproduce with another laptop, Seem like is only happen for my laptop.  the browser version may not the issue that I thought,  I tried to check with another path, and I found it.

![display setting](https://cloud.githubusercontent.com/assets/8347502/22876549/da407a46-f203-11e6-861e-c872113adbb1.png)
My screen display setting was set to "125% (Recommend)"
![125](https://cloud.githubusercontent.com/assets/8347502/22876522/b7dcfaba-f203-11e6-9db7-3a896619fc0e.png)

I have changed to "100%"
![100](https://cloud.githubusercontent.com/assets/8347502/22876542/cd799ab8-f203-11e6-8d05-4cbb22a70975.png)

and then i go to you link example link http://dabeng.github.io/OrgChart/export-orgchart/, and i tried to export it from chrome.  And now the result was correctly.
![myorgchart-correct](https://cloud.githubusercontent.com/assets/8347502/22876626/2ec6a8f6-f204-11e6-8c87-ebd8d88ff9a9.png)

Your org chart lib is very good and I hope this information help you to improve your lib.

**Comment by dabeng** [comment]
Thank you very much 😊 , I have updated readme according to your exploration.
