### ISSUE TITLE
how to handle database with parent_id table?

### ISSUE THREAD

**Issue by TatangRustama** [dabeng/OrgChart#154]
hi, nice work you've done here. 
i have try it and its awesome, easy to customize based on what we need.
but i wonder if this chart can handle database with parent_id table. since we have current database with lots of tables and fields. previously we use tree based charts for showing parents and children relatives diagrams. 
each dataset consist of 3 important tables,which is ID, Parent_id, and Name. rows will be the children of other data if those data in parent_id table are the same with data in ID table of other data.
i wonder if this orgchart can also handle it too. is there any easy way to do that? if so, how do you guys do it, maybe some example scripts to change the database output or tips will also work. 
thanks

**Comment by dabeng** [comment]
Hi @TatangRustama , I'm sure that I have read your special demand seriously but not yet get your point. Maybe it will get better result if you demonstrate your idea with a picture or draft. 😊

**Comment by TatangRustama** [comment]
oh gosh, i loled.  sorry i mean if i have a database with fields such as below,

id| name | parent_id
----|------|----
| 1 | ELECTRONICS | NULL |
| 2 | TELEVISIONS |  1 |
| 3 | TUBE  |  2 |
|  4 | LCD  |  2 |
|  5 | PLASMA  |  2 |
| 6 | PORTABLE ELECTRONICS |      1 |
| 7 | MP3 PLAYERS | 6 |
| 8 | FLASH  | 7 |
|  9 | CD PLAYERS  | 6 |
|10 | 2 WAY RADIOS  | 6 |

as the table shown, 
1. ELECTRONICS will become parent while TELEVISIONS and PORTABLE ELECTRONICS will be its children
2. TELEVISIONS become parent for TUBE, LCD and PLASMA,
 3. and so on.
can orgchart handles those data based on **id** and **parent_id** fields?

**Comment by dabeng** [comment]
Hi @TatangRustama ，what you need is just a algorithm for constructing the standard datasource for orgchart plugin. In fact, it's a external helper function for orgchart. Maybe my another repo [json-loop](https://github.com/dabeng/JSON-Loop) can help you.

**Comment by dabeng** [comment]
Hi @TatangRustama , I create a [demo](http://codepen.io/dabeng/pen/mRZpLK) on codepen.io, hope you like it . Although it's a js implementation, I believe you can create the server-side version(java, python, and so on) of the algorithm of constructing the datasource for orgchart plugin 😊

**Comment by TatangRustama** [comment]
great!!. love how it works.!
thankyou dabeng.

**Comment by kipa-zhang** [comment]
@TatangRustama 
I have the same table like yours.Here is my solution.
**arr** is the result from DB,like [{},{}...]
（Node.js）
`function makeJson(arr){
    let rootObj = {};
    for(let i = 0;i<arr.length;i++){
        if(arr[i].ParentID == 0){
            rootObj = makeNodeJson(arr[i]);
        }
    }
    return add_children(rootObj,arr);
}
function add_children(ParentObj,arr){
    let children = [];
    let children_num = [];
    for(let i = 0;i<arr.length;i++){
        if(arr[i].ParentID == ParentObj.id){
            let child = makeNodeJson(arr[i]);
            //递归
            child = add_children(child,arr);
            //child 的个数
            children_num.push(child.title);
            children.push(child);
        }
    }
    if(children.length != 0){
        ParentObj.children = children;
        var _num = 0;
        for(let n in children_num){
            _num += parseInt(children_num[n]);
        }
        ParentObj.title = ""+ _num;
    }

    return ParentObj;
}
//单个节点json格式
function makeNodeJson(obj){
    let child = {};
    child.name = obj.OrgName;
    child.id = obj.OrgID;
    child.title = obj.Num+"";//显示所有人数
    child.class = "top-level";
    return child;
}`

**Comment by kipa-zhang** [comment]
@TatangRustama 
使用递归（recursion）创建JSON数据
我使用的这种方式解决的

**Comment by CharlesV7international** [comment]
Hey @dabeng it seems like your [demo](https://codepen.io/anon/pen/GMqJOO) is not showing anything.
I tried to make some changes so an orgChart would appear but I got nothing... Is it normal? If not could you update it?

**Comment by challe** [comment]
@dabeng is it possible to do the same thing but in reverse? That is, to "flatten" the JSON so that it can be stored in the database again?
