### ISSUE TITLE
In the demo, siblings collapse into each other 

### ISSUE THREAD

**Issue by DelightedD0D** [dabeng/OrgChart#16]
In the demo located at http://dabeng.github.io/OrgChart/drag-drop/ clicking the infacing arrows on either side of an element will collapse all of that elements siblings into the clicked element. 

It seems that this is intended behaviour as if meant to focus on the selected node and its children  but it strikes me counter-intuitive. This behaviour makes it seem like the hidden elements are children of the clicked element not its siblings which is not the case.

I feel like this will cause confusion with my users. I would need to make one of the following changes in order to use this:

1. Hide the left and right arrow using CSS to eliminate confusion
2. Change the left and right icons from an arrow to something that more intuitively suggests a focusing action, like a magnifying glass perhaps

![screenshot at may 09 12-43-57](https://cloud.githubusercontent.com/assets/8271955/15122532/36c5e9fa-15e5-11e6-8d65-6ef88692942e.png)

**Comment by dabeng** [comment]
Hi @DelightedD0D . Thank you so much for your deep and detailed analysis about expand/collapse nodes feature.
While, left&right arrows help users to expand/collapse sibling nodes, top arrow expands/collapses ancestor node, bottom arrow expands/collapses descendant nodes, all of those are basic parts of core behavior of OrgChart plugin that shouldn't be modified lightly. 
Imagine if siblings nodes are  hided and their child nodes are not hided, it's indeed a weird user experience and cause confusion.

**Comment by DelightedD0D** [comment]
I get what you're going for but it looks odd. In the image on the right, with the siblings collapsed, There's no indication that elements are hidden it just looks like "Chun Miao" only has one child. Overall, great job. My only critique is just that there could be something to show that one sibling is focused and that there are others that are hidden.
