### ISSUE TITLE
Circular Reference

### ISSUE THREAD

**Issue by TechnicalRhino** [dabeng/OrgChart#163]
I was creating a chart where I need to show some circular references. Is that possible via orgchart? Because my other requirements are superbly matches with this tool.

**Comment by dabeng** [comment]
Hi @TechnicalRhino , you mean you want a direct connecting line between the two nodes disregarding the levels.

**Comment by TechnicalRhino** [comment]
Hello @dabeng . Yes Something like that. That might show some loosely described relationship.

**Comment by dabeng** [comment]
sorry @TechnicalRhino , orgchart plugin is designed to describe the standard tree-like structure. Describing the loose structure like you mentioned is beyond its capability. Maybe d3.js can help you.
