### ISSUE TITLE
zoom limits

### ISSUE THREAD

**Issue by korenanzo** [dabeng/OrgChart#166]
Hi,

is it possible to set  a zoom-in and zoom-out limit? 
Especially if you are using an Apple trackpad, the orgchart risks to disappear.

here it is a video example
https://dl.dropboxusercontent.com/u/1181512/zoooom.mov

**Comment by dabeng** [comment]
Hi @korenanzo , thanks a lot for your great advice. I have released version 1.3.6 which allows uses to set zoom-in/zoom-out limit. You can try out [pan-zoom demo](http://dabeng.github.io/OrgChart/pan-zoom/) again :blush:
