### ISSUE TITLE
Can I call my customized function after drop over?

### ISSUE THREAD

**Issue by ruifeng99** [dabeng/OrgChart#17]
Dear dabeng,

Thanks for your great work. Can I call my customized function after drop over? How?

**Comment by dabeng** [comment]
No problem, I'm planning to expose a particular event "drop.oc.node"

**Comment by dabeng** [comment]
Hi @ruifeng99 , in version 1.0.6, we has exposed a new event -- nodedropped.orgchart. You can place your customized function in the handler of this event. For more details, please refer to example [drag & drop](http://dabeng.github.io/OrgChart/drag-drop/)
