### ISSUE TITLE
Click event

### ISSUE THREAD

**Issue by krosoftware** [dabeng/OrgChart#171]
Hello
do you have plans to include Click event? Or, is there any other way to get info for clicked node?
Thank you.

**Comment by dabeng** [comment]
Hi @krosoftware , could you explain what's the meaning "get info"?

**Comment by krosoftware** [comment]
Hello @dabeng , I mean get id and other node details. If you have:
`var datasource = {
  'id': '1',
  'name': 'Su Miao',
  'title': 'department manager',
  'relationship': '111',
  'children': [
    { 'id': '2','name': 'Tie Hua', 'title': 'senior engineer', 'relationship': '110' },
    { 'id': '3','name': 'Hei Hei', 'title': 'senior engineer', 'relationship': '111' }
  ]
};
`
then I would like get id, relationship for clicked node.
Thank you.

**Comment by krosoftware** [comment]
Hello @dabeng , any idea how to get id of clicked node?
Thank you.

**Comment by krosoftware** [comment]
Anybody, please?

**Comment by dabeng** [comment]
Hi @krosoftware . Plugin orgchart enables users to customize their structure of datasource and construct the internal content of every node, so if you datasource includes "id" field, you get the node info with the following code snippets:
```js
      'createNode': function($node, data) {
        $node.on('click', function() {
          alert(data.name + ' - ' + data.title);
        });
      }
```
This is the complete [demo](http://codepen.io/dabeng/pen/oZBEMo) for you 😊

**Comment by krosoftware** [comment]
Awesome, thank you so much.

**Comment by kipa-zhang** [comment]
@dabeng 
I also want to modify the node, like the title ,name
Do you have an idea ?
