### ISSUE TITLE
Is it possible to re-draw the org chart after updating the data source?

### ISSUE THREAD

**Issue by nattrass** [dabeng/OrgChart#173]
At the moment to change the data source I'm removing all of the children from the element I called orgChart against. This seems to destroy the current Org Chart.
```js
$('#orgChartContainer').children().remove();
```
and then call orgChart() again against $('#orgChartContainer') with an updated data source.
Should I be destroying/re-creating the org chart? Or is there a better way?

I need to change the datasource as I'm changing the key of the root node I'm using to render the org chart ie, "/api/orgchart/{nodeKey}"

**Comment by dabeng** [comment]
Hi @nattrass , the basic mechanism of orgchart plugin is to build up a tree-like structure and add it into the container element. So you can use 
```js
$('#orgChartContainer').empty();
```
to remove the existing tree-like chart and then use
```js
$('#orgChartContainer').orgchart({ ... });
```
to create new tree-like chart 😊

**Comment by nattrass** [comment]
Thanks @dabeng. I wasn't sure if there would be event handlers left hanging about. Done some reading and I can see that empty() will trash everything.
