### ISSUE TITLE
Add more fields

### ISSUE THREAD

**Issue by Zmove** [dabeng/OrgChart#180]
Hello,

For what I've seen in the example, it seems you can only have a 'name' and a 'content' fields.

I need to add more fields like image, url, birthdate, etc... is it doable actually ?

If no, do you think it's an idea that could be planned in a near future ?

Thanks

**Comment by dabeng** [comment]
hi @Zmove, option createNode can help you customize the structure of node

**Comment by dabeng** [comment]
```js
'createNode': function($node, data) {
  // here, parameter data includes all the fields
}
```

**Comment by z354392349** [comment]
您好，您可以说的更详细一点么，我现在继续这个参数，谢谢您。

**Comment by z354392349** [comment]
Hello, I'm glad to be able to use your work. I'll continue to use createNode. Could you please tell me more details, or give me a case, thank you

**Comment by gonzalez-diego** [comment]
You can add your own data by adding it to the current node as a property by saving it from inside createNode callback.

`
var datasource = {
    'id': 1,
    'name': 'MyNameIs_1',
    'job': 'CEO',
    'children': [
    {
        'id': 2,
        'name': 'MyNameIs_2',
        'job': 'sub-director1'
    },
    {
        'id': 3,
        'name': 'MyNameIs_3',
        'job': 'sub-director2'
    }
    ]
}
var oc = $('#chart-container').orgchart({
    'data': datasource,
    'parentNodeSymbol': 'fa-th-large',
    'nodeContent': 'job',
    'createNode': function ($node, data) {
        $node.name = data.name;
        $node.username = data.username;
        $node.job = data.job;
    }
});
`

**Comment by doarsal** [comment]
http://creappti.com/scripts/orgChart/

**Comment by etrok** [comment]
To concat with existed field:
```
    $('#chart-container').orgchart({
      'data' : datascource,
      'nodeContent': 'title',
      'createNode': function ($node, data) {
    	  $node.children('.title').append(data.job);
          }
    });
```
