### ISSUE TITLE
Move left / right

### ISSUE THREAD

**Issue by Zmove** [dabeng/OrgChart#181]
Hello,

Actually, the drag & drop feature only allow to reorder nodes in a parent / child way. It would be great to be able to reorder nodes too.

Could be useful to add some methods to do this via API too.

**Comment by dabeng** [comment]
Hi @Zmove , plugin orgchart is designed to describe the tree-like structure, so I think the left/right order of nodes is not concern of orgchart.

**Comment by Zmove** [comment]
I'm not sure, for example we can easily consider a menu as a tree-like structure and the order of element in menu are important. Another example a family tree where the order is also important.
