### ISSUE TITLE
How to remove zooming effect in pan and zoom style of Org Chart

### ISSUE THREAD

**Issue by Lakshmi1994** [dabeng/OrgChart#182]
In the pan and zoom, i dont want the OrgChart to zoom in or out on mouse movement.

How do i do that? Please suggest 

Thanks in advance :)
Lakshmi

**Comment by dabeng** [comment]
Hi @Lakshmi1994 , you just need to disable zoom with settings:
```js
zoom: false, // of course , you can ignore this option because default value is also false
pan: true
```

**Comment by Lakshmi1994** [comment]
That was quite simple and interesting!!
Thanks :)

Regards,
Lakshmi
