### ISSUE TITLE
OrgChart for React

### ISSUE THREAD

**Issue by fgiarritiello** [dabeng/OrgChart#186]
Hi, has anyone attempted to use orgChart with React. If so could you please share some guidance? Thanks

**Comment by dabeng** [comment]
Sorry @fgiarritiello , I don't like the syntax style of React because of its complexity. So I'm going to build up angular version of orgchart. While, maybe in near feature, I'll publish Vue.js version of orgchart.

**Comment by chenxu7601257** [comment]
Looking forward to the angular version of orgChart

**Comment by hkedia321** [comment]
Hi @dabeng looking forward for the react version.

**Comment by sibelius** [comment]
@dabeng have you changed your mind?
