### ISSUE TITLE
Admin node

### ISSUE THREAD

**Issue by user165** [dabeng/OrgChart#187]
Hi @dabeng , it would a nice feature to have an option to add an admin node to the chart, with a child node to the side rather than below (similar to "General Office" node in picture below). 

I think you are doing something similar with the vertical nodes. Is this feasible? Thanks again for providing such a useful library.
<img width="960" alt="screen shot 2017-03-16 at 6 06 34 pm" src="https://cloud.githubusercontent.com/assets/26174119/24022381/1f74670c-0a74-11e7-9935-a165f842a8cb.png">

**Comment by dabeng** [comment]
I have to say it's an awesome chart. I wonder wether the above is created with orgchart plugin or just photoshop work.

**Comment by dabeng** [comment]
@user165, I know "admin node" is cool feature and maybe "assistant node" is accurate, but it will break the rules of hierarchy relationships of current orgchart. So I think it's a good choice to make use of createNode callback to create an isolated "assistant node".

**Comment by user165** [comment]
Hi @dabeng, Thank you for your response. I found the org chart image online - not sure how it was generated.

Can you elaborate on how to create an isolated "assistant node" using createNode callback? Thanks!

**Comment by gabymcr123** [comment]
Hi @dabeng, Please help us with how to create an isolated "assistant node" using createNode callback? Thanks!

**Comment by dabeng** [comment]
@user165 , Hope this [demo](https://codepen.io/dabeng/pen/WXQqxz) can help you 😊

**Comment by dabeng** [comment]
<img width="777" alt="screen shot 2017-11-02 at 6 41 28 pm" src="https://user-images.githubusercontent.com/5689075/32321920-b14b21c2-bffd-11e7-905b-e5f44df78908.png">

**Comment by dabeng** [comment]
The core logic code is shown below:
```js
      createNode: function($node, data) {
        if (data.title === "general manager") {
          var assistantNode =
            '<div class="assistant-node"><div class="connector"/><div class="title"><i class="fa fa-user-circle-o symbol"></i>Dan Dan</div><div class="content">general office</div><i class="edge verticalEdge bottomEdge fa"></i></div>';
          $node.append(assistantNode);
        }
      }
```
