### ISSUE TITLE
orchart for angular2

### ISSUE THREAD

**Issue by hengkyz** [dabeng/OrgChart#189]
anybody know where i can get example orchart for angular2?
thank you

**Comment by dabeng** [comment]
Sorry @hengkyz , I don't like the syntax style of Angular because of its complexity. So I'm going to build up angular version of orgchart. While, maybe in near feature, I'll publish Vuejs version of orgchart.

**Comment by saurabhbhandari2006** [comment]
Hi dabeng,
Is Angular version of OrgChart is ready.
