### ISSUE TITLE
how about zoom in OrgChart using button ?

### ISSUE THREAD

**Issue by irsalshabirin** [dabeng/OrgChart#203]
please, i want this :) thanks 👍 💯

**Comment by nengc** [comment]
`    $('#aZOut').on('click',function(){
        var e = new WheelEvent("wheel", {deltaY: 100});
        document.getElementById('chart-container').dispatchEvent(e);
    });
    $('#aZIn').on('click',function(){
        var e = new WheelEvent("wheel", {deltaY: -100});
        document.getElementById('chart-container').dispatchEvent(e);
    });`

**Comment by nengc** [comment]
```js
    $('#aZOut').on('click',function(){
        var e = new WheelEvent("wheel", {deltaY: 100});
        document.getElementById('chart-container').dispatchEvent(e);
    });
    $('#aZIn').on('click',function(){
        var e = new WheelEvent("wheel", {deltaY: -100});
        document.getElementById('chart-container').dispatchEvent(e);
    });
```

**Comment by nengc** [comment]
You can do like that  O(∩_∩)O~

**Comment by dabeng** [comment]
@nengc , cool solution :blush: and you remind me that it would be better to expose the setChartScale() method.

@irsalshabirin , from vsersion 1.3.7 of orgchart, you can use the following code snippets to scale chart
programatically.
```js
$('#chart-container').orgchart('setChartScale', $('.orgchart'), 1.2);
```

**Comment by CharlesV7international** [comment]
Both of your suggestions didn't work for me. 
This was my solution:

`var currentZoom = parseFloat($('#chart-container').css('zoom'));

$('#zoomOut').on('click', function () {
    $('#chart-container').css('zoom', currentZoom -= 0.1);
});
$('#zoomIn').on('click', function () {
    $('#chart-container').css('zoom', currentZoom += 0.1);
});`

and add style="zoom: 1;" in your chart-container
