### ISSUE TITLE
What is the callback function to identify the elements are rendered?

### ISSUE THREAD

**Issue by jeevasusej** [dabeng/OrgChart#205]
I want to trigger a method after all the elements are rendered by the orgChart.

I have used the **document.ready**. But it doesn't work at all.

Which event  I should use to check whether the elements are rendered completely?
If not there any event, I need urgent fix for this.

Please help ..

**Comment by jeevasusej** [comment]
https://github.com/dabeng/OrgChart/pull/208

**Comment by dabeng** [comment]
Hi @jeevasusej ,you can find event "init.orgchart" and callback "initCompleted" since orgchart v1.5.1. Here's the [Demo](https://codepen.io/dabeng/pen/vZjpaw)
