### ISSUE TITLE
Cannot show chinese characters

### ISSUE THREAD

**Issue by ChegnduJackli** [dabeng/OrgChart#209]
When I type chinese characters, it shows ????, any solution for this?

**Comment by dabeng** [comment]
Hi @ChegnduJackli , your issue has nothing to do with orgchart plugin itself. It's related to charset code of your web pages.Please reference to **[Demo](http://dabeng.github.io/OrgChart/custom-template/)** and tell me whether you see the right chinese characters :blush:
