### ISSUE TITLE
collapse siblings to right and left respectively..on the basis of an arrow

### ISSUE THREAD

**Issue by ssameer07** [dabeng/OrgChart#21]
First of all great work guys.

I just have a question about collapsing and expanding the siblings on the basis of arrow.
Currently clicking on any horizontal arrow results into collapsing all siblings.
Can we make this collapsing more appropriate by considering the arrow's direction.
For example., collapse/hide only right side nodes when right side arrow is clicked and and same for left and expanding/showing up the nodes.

Please share your thoughts on this.

Thanks....

**Comment by dabeng** [comment]
Hi @ssameer07 , can you explain your particular demand to show that collapsing/expanding left/right sibling nodes is more useful than collapsing/expanding all sibling nodes at the same time.

**Comment by ssameer07** [comment]
Hi @dabeng, I am concerned about navigation purpose. Unlike vertical navigation if we could also collapse/expand the nodes horizontally. We can consider this as feature as if one wants to compare one or more nodes having common root at the same time this will help to serve the purpose.

Thanks...

**Comment by dabeng** [comment]
OK, got it. I promise this feature will be available in version 1.1.0.

**Comment by dabeng** [comment]
Hi @ssameer07 , option toggleSiblingsResp in relaese 1.0.9 is what you need, just enjoy it :blush:

**Comment by ssameer07** [comment]
Hi @dabeng , amazing work man...this works perfectly...thanks a lot....
