### ISSUE TITLE
Center orgchart

### ISSUE THREAD

**Issue by cargie** [dabeng/OrgChart#214]
I have an issue on a very large chart. How will I put the chart to center or fit to screen so it will be easy to zoomout/in? Thank you

**Comment by clickstudio** [comment]
I would also love this. Very painful to have to scroll to the middle every time it loads.

**Comment by dabeng** [comment]
What's your favorite vertical-horizontal alignment ? top-center or middle-center ?

**Comment by dabeng** [comment]
Another thing, does it make sense to scale a huge orgchart to make it fit to screen? It will be a mass.

**Comment by clickstudio** [comment]
Here is the issue I'm facing with chart charts

https://www.awesomescreenshot.com/image/2573365/91eb33cb2f7fd4740a516f854f3ca765

See the top person in the chart is always off page and a long way to the right. 
It would be great to have a way to center the chart and even have a way to set the initial zoom so it fits on the page.

another great feature would be a way to select a name from a drop down and the person can be located without having to scroll around looking for them.

**Comment by clickstudio** [comment]
This is a good example of how the top level node is always centered
https://www.basicprimitives.com/index.php?option=com_local&view=local&Itemid=40&lang=en

This is a good example of being able to search for a node
http://www.getorgchart.com/Demos

**Comment by dabeng** [comment]
Hi @cargie @clickstudio , I created a **[Demo](https://codepen.io/dabeng/pen/LLqwrK)** for you. Hope you like it :blush:

**Comment by clickstudio** [comment]
Thanks @dabeng. Much appreciated!!

**Comment by GeekWiinik** [comment]
Hi dabeng thanks for OrgChart, maybe not the same problem but when you collapse a node where is to deep some times it lost from screen, i made this, hope helps to solve the problem..
```

 $('.verticalEdge').on('click', function()
              {
                  setTimeout( function()
                  {
                      centerChart();
                  }  , 500 );
              });

  function centerChart()
            {
                    // Do something after 1 second
                    var parent = $('#chart-container');
                    var child = $('.orgchart');

                    child.css("position","absolute");
                    child.css("top", ((parent.height() - child.outerHeight()) / 2) + parent.scrollTop() + "px");
                    child.css("left", ((parent.width() - child.outerWidth()) / 2) + parent.scrollLeft() + "px");
                    child.css("transform",'matrix(1, 0, 0, 1, 0,0)');            
            }
```

**Comment by JamesZhang19850319** [comment]
hi，there
@dabeng @GeekWiinik @clickstudio @bigfox 
How to center the header for the chart-container, My website is http://senboll-xa.3322.org:8888/frame/paradox.html.

**Comment by moreishi** [comment]
@dabeng Is there a way you can make a 'l2r' center position? Just like this [Demo](https://codepen.io/dabeng/pen/LLqwrK)

**Comment by cppmyjob** [comment]
@dabeng your [Demo](https://codepen.io/dabeng/pen/LLqwrK) works fine for static data only when initCompleted is fired. I would like the same thing for dynamic loaded data. Is there a way to detect that data is loaded and i can handle this event?

**Comment by doarsal** [comment]
http://creappti.com/scripts/orgChart/

**Comment by hadihashem** [comment]
Hi @doarsal 
Your demo looks very nice
Can you please share you code behind?
Regards

**Comment by doarsal** [comment]
@hadihashem http://creappti.com/scripts/orgChart/OrgPHPMySQL.rar

**Comment by hadihashem** [comment]
Hello @doarsal 
Thank you for sharing

I noticed one issue which I'm also facing: data loading doesn't work on IE
I'm facing the same problem due to the use of custom templates
https://rawgit.com/dabeng/OrgChart/master/demo/custom-template.html

Besides, I'm struggeling with html2canvas, more precisly with unicode font rendering
https://github.com/niklasvh/html2canvas/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3AUnicode
Did you experience such problem before?

I appreciate you help
Regards

**Comment by dromeroSL** [comment]
> This is a good example of how the top level node is always centered
> https://www.basicprimitives.com/index.php?option=com_local&view=local&Itemid=40&lang=en
> 
> This is a good example of being able to search for a node
> http://www.getorgchart.com/Demos

Hi @clickstudio, you could do the search?

**Comment by emad22552** [comment]
i use this function on each change to center orgchart:
```javascript
function setContainerMiddle(){
    // set positopn of scrollbar middle
    var outerContent = $('#chart-container');
    var innerContent = $('#chart-container > div');
    outerContent.scrollLeft((innerContent.width() - outerContent.width()) / 2);
    outerContent.scrollTop((innerContent.height() - outerContent.height()) / 2);
}
```

**Comment by FreezeSoul** [comment]
nice solution! thks

**Comment by GaryFrewin** [comment]
Hi. I'm having an issue with a large orgchart, when I press a button to collapse the chart down to just the top node, it disappears off canvas. 

I tried creating a center button using both bits of code from Emad22522 and GeekWiinik, but the behaviour is erratic. It only seems to centre some of the time, other times it is off centre and sometimes, usually when the chart is fully expanded, it moves the whole thing off the canvass. 

Any ideas most welcome

**Comment by ashkyn** [comment]
> The functions above did not work for me... perhaps something to do with panning?? I'm not sure, anyway, the below works:
> 
>...Code Here...
> 
> You may need to switch childX and childY depending on your charts orientation.

Hi, could you elaborate as to how I would go editing that to work with the normal chart orientation?
No matter what I do, this seems to flip it 90 degrees.

**Comment by abasina09** [comment]
.orgchart{
      display: flex!important;
    display: flex;
    align-items: center;
    justify-content: center;
}

**Comment by sabatale** [comment]
@abasina09 Simple, I like it. Have you looked into getting an auto-zoom as well by any chance? (centered with a zoom level that shows the whole chart as a starting point)

**Comment by vinit-poojary** [comment]
> .orgchart{
> display: flex! important;
> display: flex;
> align-items: center;
> justify-content: center;
> }

export to does not work when this CSS is applied
