### ISSUE TITLE
Enable and Disable Zoom and Pan

### ISSUE THREAD

**Issue by clickstudio** [dabeng/OrgChart#217]
Sorry this isn't an issue but is it possible to enable the pan and/or zoom with an onclick action or similar ?

**Comment by dabeng** [comment]
Hi. @clickstudio, click what? "Enable pan button "?

**Comment by clickstudio** [comment]
I currently have a checkbox that users can click to enable both the pan and zoom but it requires them to submit the form where I then set the JavaScript parameters.

https://www.awesomescreenshot.com/image/2573365/91eb33cb2f7fd4740a516f854f3ca765

Is it possible switch on or off the pan and zoom without reloading the page ?

**Comment by dabeng** [comment]
Hi @clickstudio , since version 2.0.1 users are allowed to Enable and Disable Zoom and Pan with setOptions() method.

**Comment by clickstudio** [comment]
That's great, Thanks @dabeng :-)

**Comment by jonalxh** [comment]
Currently not working with Vue wrapper, I've set `pan: false` on **OrgChart initialization** and does not work.
Setting `this.chart.setOptions("pan", false) ` neither work.

Is it currently working? Whats the correct way to disable pan in 2020?
