### ISSUE TITLE
ajaxURLS call back

### ISSUE THREAD

**Issue by lordzpipo** [dabeng/OrgChart#22]
hi @dabeng ,
i am trying your plugin, everything run good,
but i found a bug in ajaxURL function
when i call children function, server side return json data,
but the plugin cannot parse the json data on line 541
`if (data.children.length)`,
 if will return 
`jquery.orgchart.js:541 Uncaught TypeError: Cannot read property 'length' of undefined`
and my solution is add `dataType: "JSON"` on line 538
like this : ` $.ajax({ 'url': opts.ajaxURL.children + nodeId + '/',dataType: "JSON" })`

hope help :D

**Comment by dabeng** [comment]
Hi @lordzpipo . Literally, this bug implies that the returned data doesn't has "children" property. Are you sure you back-end returns JSON object like the following format:
{
  'children': [
    {...............},
    {...............},
    {...............}
  ]
}

**Comment by lordzpipo** [comment]
hi @dabeng ,
i am returning JSON data with php `json_encode()`
and yes, i got "chidren" property in my data,
btw, i solve it when i add `dataType:"JSON"` to line 538.

**Comment by dabeng** [comment]
All right. Thanks for your testing. It seems that it's necessary to set dataType to "json" in file juery.orgchart.js.

**Comment by rwitchell** [comment]
@dabeng why should the node need a 'children' property? if the property isn't there, it should be considered empty.

**Comment by logicplayer1** [comment]
hi @dabeng,

I am also using your plugin, its perfect i have checked all its demos, its really fantastic.

Now i am using it with ASP.NET web forms, initial datasource load from ajax call is good but if i load children through ajax its not working as you have not give the demo of remote data load on demand.

Please help me in this matter .
Thanks
