### ISSUE TITLE
Node Color

### ISSUE THREAD

**Issue by whizkris** [dabeng/OrgChart#227]
Hi,
Thanks for making such a great tool for OrgChart. We have tried to customize it to use, but we are stuck at one point. We are trying to indicate "Vacancies" in the chart and show them in a different color. While coloring a full level seems possible, coloring only a select node seems to be missing from our eye. Can you help us?

**Comment by dabeng** [comment]
Wow! I'm glad to hear that you applied orgchart plugin in your web apps. Regarding the bug you mentioned, could you send me a demo on jsfiddel or codepen, I'll fix the bug for you ASAP:blush:

**Comment by dabeng** [comment]
This **[Demo](https://codepen.io/dabeng/pen/zBNbqV)** may give you some ideas and inspiration.

**Comment by whizkris** [comment]
Hi,
Thanks for the reply. My problem is this:
The color of only one node has to change. Btw, I am using PHP & MySQL. 

I am attaching a sample image of the requirement  https://prnt.sc/fwktny

**Comment by NielsNet** [comment]
You could simple give the nodes you want to highlight a className in your dataSource, while not setting it for others. In that case you could set different rules for the highlighted nodes.
This [demo](
https://codepen.io/anon/pen/JyYGQg) should help understand what I mean.
In case you want to format using the content of the title area you could probably do so by using JavaScript.

**Comment by whizkris** [comment]
Thanks @NielsNet !!! Got it working !
