### ISSUE TITLE
Expnad & collapse all node 

### ISSUE THREAD

**Issue by pc1990** [dabeng/OrgChart#235]
How to apply "all expnad & collapse " by click on button?

**Comment by lfer34** [comment]
I would also like this.

**Comment by dabeng** [comment]
Leave it to me :blush:

**Comment by dabeng** [comment]
Hi @pc1990 , @lfer34 , hope you guys like this **[Demo](https://codepen.io/dabeng/pen/VWgdzp)**.

**Comment by lfer34** [comment]
Great job! thanks

**Comment by lfer34** [comment]
hey! When we hide left/right sibling nodes then collapse all and Expand all, we don't have all nodes
![capture](https://user-images.githubusercontent.com/11297217/28265971-c21bd6b4-6af2-11e7-96ae-2e29dfa6002c.PNG)
Is it possible to render all nodes visibles when expanding all ?
Bests regards.

**Comment by jvsiren** [comment]
@dabeng Is it possible with On Demand loading? And add some limit, e.g. max depth 4, so that it doesn't expand all if the hierarchy is massive?
