### ISSUE TITLE
how refresh chart?

### ISSUE THREAD

**Issue by pc1990** [dabeng/OrgChart#236]
At the time of calling the service to disply the chart each time a button is clicked a new chart is displayed in the same "view".
How to refresh the chart without refresh page?

**Comment by dabeng** [comment]
Hi @pc1990 , sinve v2.0.0 of orgchart, you can refresh, re-init or reload data with the following code snippets:
```js
var oc = $('#chart-container').orgchart({ ... }); // variable oc is an instance of class OrgChart
oc.init({ ... }); // re-initialize the orgchart with new options
```
Besides, I created a [Demo](http://dabeng.github.io/OrgChart/reload-data/) for you. Hope you like it :blush:

**Comment by pc1990** [comment]
Thanks a lot.

**Comment by lienyun** [comment]
Hi, if i dont want to use jQuery, i use the ES6 version, how to refresh the orgchart?
There is no init function in the docs.
Plz help me. Thank you!
