### ISSUE TITLE
Titles and Content in standard UL/LI

### ISSUE THREAD

**Issue by ActiveScottShaw** [dabeng/OrgChart#24]
A couple of bits which don't seem straight forward and not really documented that I can see.

1) We are using just the 'standard' UL/LI list .... In the LI's how do you define the TITLE and CONTENT? I know you can add 'nodeContent' into the jquery options ... but what value does it need and what is the structure of the LI's?

2) Changing the WIDTHS ... we want to make the titles longer so you get to see more content .... do we then have to go through the CSS and change all the widths / margins?

**Comment by dabeng** [comment]
Hi @ActiveScottShaw , tanks for your use orgchart plugin. You mentioned two good scenarios

1) In fact, ul list  is not preferred datasource for orgchart. JSON datasource is more lightweight, flexible and easy to maintain. In you choose ul list to build up orgchart, it means that you just wanna use html content of li to fill in the title section of orgchart node.

2) If you use default orientation(top to bottom), you just need to override default width setting in your own css file as shown below.
```
/* node styling */
.orgchart .node {
  ...
  width: 130px; // override this default setting
  ...
}
```

**Comment by ActiveScottShaw** [comment]
Hi thanks for the clarification!

We had a play had came to the same conclusion and just ended up using JSON instead :)

Yep we also ended up just tweaking the CSS for the widths as well

:)

**Comment by 0312birdzhang** [comment]
Hello,@dabeng ,how to set node style if my orientation is l2r?
