### ISSUE TITLE
are you still supporting IE ?!

### ISSUE THREAD

**Issue by mFouadShaheen** [dabeng/OrgChart#243]
I've tried using it in IE11 but it gives me error 
![error](https://user-images.githubusercontent.com/18028854/28076111-eb00bf84-665d-11e7-91c1-14975d9dcc00.PNG)

i also downloaded the jquery examples but it didn't work either 
that happens starting from version **2.0.0**

my IE version 
![ie version](https://user-images.githubusercontent.com/18028854/28076197-2b4d75aa-665e-11e7-9195-bf63a3a8ee95.PNG)

is there any soultion for this ?!

thanks

**Comment by toshetoo** [comment]
You must use a polyfill as the IE does not support promises. Consider including bluebird.js also.

**Comment by warrenspe** [comment]
Further to this; there seems to be a syntax error which IE complains about.  
On line 46 we begin to define an object, set onto OrgChart.prototype.
`  OrgChart.prototype = {`
On lines 48-183 we add the first item to that object:
```
    init: function (opts) {
        ...
    },
```

On line 185 (and repeatedly basically until the end of the file) we appear to define a function _within_ the object definition.
```
    setOptions (opts, val) {
      if (typeof opts === 'string') {
```
...
```
    panStartHandler (e) {
      var $chart = $(e.delegateTarget);
```
etc
