### ISSUE TITLE
ul list

### ISSUE THREAD

**Issue by fyher** [dabeng/OrgChart#244]
How I define the name and title if I use the ul list ? 
thanks

**Comment by dabeng** [comment]
Hi @fyher , from my point of view, ul datasource is not suitable for build up complex internal structure of node. I recommend you to use option "nodeTemplate" to create complex node structure. For details, please reference to this **[Demo](http://dabeng.github.io/OrgChart/custom-template/)**.

**Comment by dabeng** [comment]
Oh, I almost forgot. Option nodeTemplate is exposed since version 2.0.2 :blush:
