### ISSUE TITLE
deactivate collapse

### ISSUE THREAD

**Issue by der-robert** [dabeng/OrgChart#25]
Hi, is it possible without changing too much code?

**Comment by ActiveScottShaw** [comment]
We were after the same thing ... a 'quick way' to get around it is to just hide off the 'arrows' so they can not be clicked.

**.orgchart .node .verticalEdge, .orgchart .node .horizontalEdge { display: none; }**

And then you can also remove the yellow glow with:
**.orgchart .node:hover, .orgchart .node.focused { background: none !important; }**

Would be great to be able to turn on and off the 'collapse' though!

**Comment by dabeng** [comment]
Thank you guys for your constructive discussions. I have added a valuable [tip](https://github.com/dabeng/OrgChart/blob/master/README.md#tips) to Readme that is inspired by this issue :blush:
