### ISSUE TITLE
Exporting

### ISSUE THREAD

**Issue by ActiveScottShaw** [dabeng/OrgChart#26]
We have downloaded '**html2canvas**', and turned on the '**Export**' button.

It does generate and download a png image .... but the image is always cropped.

Our Org Chart, can be quite long, so ends up having scroll bars (often both x and y axis)... is this the reason the image gets cut? ... if so is there a way to 'Force it' to be the whole area?

**Comment by ActiveScottShaw** [comment]
I also am wondering if there is also an issue with the '**orientation**' when trying yo export .... all your examples use the '**t2b**' .... we are using '**l2r**'

But as you are using CSS to rotate, this means the 'width' and 'height' go in the opposite directions, which I think will also cause issues when exporting

**Comment by dabeng** [comment]
Hi @ActiveScottShaw , you could try version 1.1.0 to test your huge Org Chart, I have fixed the bug that  exported picture is always cropped.In fact, to avoid this issue, you need some tricks based on html2canvas' new options. For more details, you could review https://github.com/niklasvh/html2canvas/issues/60
