### ISSUE TITLE
add new exportTree method.

### ISSUE THREAD

**Issue by YousefMMS** [dabeng/OrgChart#265]
create new export method, do the same behavior of "export button", instead of being an option to be added in the options object.

so developer simply can call like this

`
var oc = $('#tree-container').orgchart({
                                data: $('#data'),
                                exportButton: true // instead of being a button
                            });
oc.exportTree();
`

may be also the `exportTree()` method accept parameters like export type 'png'/'pdf'

**Comment by dabeng** [comment]
Yes. It's very helpful method. Thank you very much 😊 . I'll add it as soon as possible.

**Comment by dabeng** [comment]
Since version 2.0.5, users are allowed to export current orgchart as a png or pdf file programmatically. In other word, export() method are exposed.
