### ISSUE TITLE
Custom code

### ISSUE THREAD

**Issue by mlekoo** [dabeng/OrgChart#27]
Hello @dabeng 
I'm wondering whether it's possible to use custom html instead of default title and name? In jOrgChart there was a possibility to use any code except ul and li inside the node and the plugin was just connecting the blocks into a tree - I'm looking for such a solution, do you think that I can do that in your plugin without tons of extra coding?
Regards

**Comment by dabeng** [comment]
Hi @mlekoo , To use option createNode is the most simplest way to build up your ower node structure. I recommend you use json datasource rather than nested ul tag, because the former is more lightweight and easy to maintain.
