### ISSUE TITLE
Can you support this data?

### ISSUE THREAD

**Issue by 1449829449** [dabeng/OrgChart#278]
var testData = [
        {"id": "01", "name": '111', "parent": "01"},
        {"id": "02", "name": '2222', "parent": "01"},
        {"id": "03", "name": '3333', "parent": "01"},
        {"id": "04", "name": '4444', "parent": "01"},
        {"id": "05", "name": '5555', "parent": "01"},
    ];

**Comment by dabeng** [comment]
Sorry. Orgchart doesn't support such format.
