### ISSUE TITLE
Loading data on demand on only specific nodes

### ISSUE THREAD

**Issue by kellydx** [dabeng/OrgChart#279]
Hi, I enjoy using OrgChart so far, I wonder if there's a way to load data on demand on only 1 level of the node, I'm using local data source now. Thanks

**Comment by kellydx** [comment]
I figured it out. Great library. Thank you so much.

**Comment by thunda99** [comment]
Hi @kellydx , 
Please can you share how you figured it out?
I am trying to do same here, got no success.

Thanks
