### ISSUE TITLE
Broken layout when the page uses CSS resets

### ISSUE THREAD

**Issue by gusehr** [dabeng/OrgChart#28]
Hi @dabeng!

I've got a layout problem when the container page includes a CSS reset (e.g. yui).

![broken layout example](https://cloud.githubusercontent.com/assets/5587752/16283893/1fb6ffd2-38a5-11e6-975f-bffcded90c0b.png)

The line layout got broken when the CSS reset adds this css property:
`table{
    border-collapse: collapse
}`

I solved this issue adding this style in jquery.orgchart.css:
`.orgchart table {
 border-collapse: separate
}`

I don't know if this is the best approach to solve the issue.
What do you think?

Thanks in advance.

**Comment by dabeng** [comment]
Hi @gusehr . You are exactly right :+1: Inside orgchart plugin, the vertical lines closer to nodes are composed of left and right border of td tag, their widths are 1px, so the final width of line is 2px. For that reason, we have to set border-collapse to separate.

On the other side, the issue you encountered reminds me that it's necessary to add the following setting to the jquery.orgchart.css file
```
.orgchart table { border-collapse: separate!important; }
```
