### ISSUE TITLE
Export the orgchart with nodes containing png

### ISSUE THREAD

**Issue by CharlesV7international** [dabeng/OrgChart#285]
I'm trying to export my chart and I have a small problem. My nodes are containing a png of the employee.
When i'm exporting it(either in an img or in a pdf), it does not show the picture. 

![first](https://user-images.githubusercontent.com/32143512/31285482-68c88810-aa89-11e7-901e-29ba8314c604.png)
![second](https://user-images.githubusercontent.com/32143512/31285485-6a3f5a34-aa89-11e7-85fd-55dba372ef4f.png)

I think you should include something in there like 'exportWithImage': true

**Comment by dabeng** [comment]
Wow! You made a great orgchart :blush: . You know that jquery orgchart pluggin uses [html2canvas](https://github.com/niklasvh/html2canvas) to implement export feature. As far as I know, html2canvs can not support the img tag, so currently I'm able to expose the option like "exportWithImage" .

**Comment by CharlesV7international** [comment]
Okay, I'll try my best to explain. 

If you take your demo option-createNode.html and add:

'exportButton': true,
'exportFilename': 'MyOrgChart',
'exportFileextension': 'pdf',

and add the html2canvas and jspdf

If you click on the info of one of the nodes, you'll see the picture right?
Then if you export the orgchart, you'll get this result: 

![orgchartnotdisplayingpic](https://user-images.githubusercontent.com/32143512/33669257-ec68c32c-da6f-11e7-8718-4c14a0c61ae1.png)

I do understand that I get the chart as a picture. What I am asking is that it displays the pictures in the graph.

**Comment by CharlesV7international** [comment]
After a lot of searching, it is a cross-origin problem. jsPDF can't use images hosted on another server wich does not allow cross-origin. Since i'm getting my images from a google drive, they will never render.

**Comment by dabeng** [comment]
Hi @CharlesV7international  @erb4f1dotama @bigfox @costonb You can use this demo -- https://codepen.io/dabeng/pen/MWqMzJX to export chart with nodes containing pictures.
