### ISSUE TITLE
Height of leaf nodes are different.

### ISSUE THREAD

**Issue by vylan** [dabeng/OrgChart#286]
Just showing in the following picture, the height of the last three leaf nodes are not exactly the same. Is there any way to fix it?
[
<img width="509" alt="screenshot" src="https://user-images.githubusercontent.com/8390531/31333801-1cf62da0-acb1-11e7-8c99-eae0095560b5.png">
](url)

**Comment by dabeng** [comment]
Hi @vylan , sorry for late rely. This bug has been fixed in version 2.0.11, please try the updated [demo](https://rawgit.com/dabeng/OrgChart/master/demo/edit-chart.html) :blush:

**Comment by dabeng** [comment]
Hi @vylan , you can also try the [demo](https://codepen.io/dabeng/pen/xOxggw) on codepen.io to check the latest modification about node layout.

**Comment by vylan** [comment]
Thanks, problem solved, good job!
