### ISSUE TITLE
Support for Family Tree

### ISSUE THREAD

**Issue by ankushupadhyay09** [dabeng/OrgChart#287]
I want to create Family Tree Structure using this OrgChart, but I am not sure currently there is any support to have 2 parent nodes for one child node.
Please let me know if there is any support for Family Tree Structure.

**Comment by dabeng** [comment]
Sorry, it's an impossible mission that one child node has two or more parent nodes.

**Comment by ankushupadhyay09** [comment]
Thanks for information so I have to research more to find way to achieve Family Tree structure.

**Comment by zhangzq** [comment]
> Sorry, it's an impossible mission that one child node has two or more parent nodes.

any progress?

**Comment by Blatman** [comment]
May be of interest to someone -
Normally the structure of table/li type charts is fine fine for orgcharts but not suitable for family tree types where child nodes need multiple parents (at least 2) however if the 'person' node is reconfigured as a 'parental unit' node then FT's are possible.
eg: 
parental unit is built as such-
.title node (person)
.content node  (person details)
.partner node   (1st partner)
.pcontent node  (1st partner details)
.partner node  (2nd partner)
.pcontent node  (2nd partner details)

I have attached a sample page zip showing multi partner scenario (it uses PrimeUI/jQueryUI theming).
I've found that this style works quite well in normal t2b mode and also b2t but the l2r/r2l modes need quite a bit of work in the CSS area that I haven't quite figured out (the transforms move the goalposts somewhat).

BTW - the red numbers in the screenshot show which partner had the issue/child.

<img width="1296" alt="Screen Shot 2020-07-01 at 16 38 18" src="https://user-images.githubusercontent.com/11089335/86270410-1abf8f80-bbc3-11ea-9246-0fea355deaae.png">

[FTexample.zip](https://github.com/dabeng/OrgChart/files/4859212/FTexample.zip)

**Comment by dddesign** [comment]
I am very interested in this topic (family tree with orgchart). Are there some new developments or other ideas for family tree building? thanks for any tips!
something like this https://balkan.app/FamilyTreeJS but open source would be perfect!

**Comment by dabeng** [comment]
Hi @ankushupadhyay09 @dddesign @zhangzq @Blatman Since version 5.0.0, user are allowed to build up the family tree. You can play around the demo -- https://dabeng.github.io/OrgChart/family-tree.html
