### ISSUE TITLE
how to create an isolated "assistant node" using createNode callback? 

### ISSUE THREAD

**Issue by gabymcr123** [dabeng/OrgChart#292]
#187 

Someone has done it?

**Comment by dabeng** [comment]
Hope this [demo](https://codepen.io/dabeng/pen/WXQqxz) can help you 😊

**Comment by dabeng** [comment]
<img width="777" alt="screen shot 2017-11-02 at 6 41 28 pm" src="https://user-images.githubusercontent.com/5689075/32321911-aa7a8108-bffd-11e7-906b-31dc4364a339.png">

**Comment by dabeng** [comment]
The core logic code is shown below:
```js
      createNode: function($node, data) {
        if (data.title === "general manager") {
          var assistantNode =
            '<div class="assistant-node"><div class="connector"/><div class="title"><i class="fa fa-user-circle-o symbol"></i>Dan Dan</div><div class="content">general office</div><i class="edge verticalEdge bottomEdge fa"></i></div>';
          $node.append(assistantNode);
        }
      }
```

**Comment by gabymcr123** [comment]
thanks @dabeng

**Comment by mp93** [comment]
Hi,

Is there any way to get the assitant nodes(A1,A2,A3) as a seperate branch as shown in the figure? Can someone help me with this?
![orgchart](https://user-images.githubusercontent.com/17583022/41487209-b2d7fc54-70b5-11e8-9179-ec4df7024ff7.PNG)
