### ISSUE TITLE
Pan and Zoom

### ISSUE THREAD

**Issue by ActiveScottShaw** [dabeng/OrgChart#30]
Is there a way to '**turn off**' the **Zoom** but still be able to pan?

We want to be able to drag about, but not zoom in if possible?

**Comment by dabeng** [comment]
Hi @ActiveScottShaw , from version 1.0.9.7, you can enable pan and zoom option respectively :blush:

**Comment by ActiveScottShaw** [comment]
Awesome, that is good.

For the time being we have just 'commented' the zoom effect out anyway :)
