### ISSUE TITLE
Update a node

### ISSUE THREAD

**Issue by BFPLima** [dabeng/OrgChart#302]
Hi guys.

Does anyone know how can I refresh a specific node?

For example, I have a node and the user have changed the node title/name via popup that I have implemented. After the popup closes, my intent is to refresh this selected node?

How can I perform this?

Additional information: I use 'createNode' and 'nodeTemplate' callbacks for builnding customizeds nodes using title/name and data attributes.

Thank you very much.

**Comment by dabeng** [comment]
Hi @BFPLima , this task is entirely up to you because plugin orghcart can not predict the final internal structure of every node.

**Comment by kishan-getstarted** [comment]
is there any possibility if we just give new json to and chart just refresh particular node automatically ? currently nothing happens we have to call create method again. Please this is very necessary any chance u will work on it @dabeng ?
