### ISSUE TITLE
Cancel the drop event

### ISSUE THREAD

**Issue by achatzi78** [dabeng/OrgChart#31]
Hi.

I was wondering if it is possible to cancel the drag & drop event if some criteria are not met.  For example, I do not want an employee to be under a specific department under no circumstance.

I have already found a way to check if the dropZone should be valid or not but I have not found a way to return the dragged node to its previous position.

Is what I am asking even possible?

Thanks

**Comment by achatzi78** [comment]
After I dug around a little bit more I found a way.

First of all I moved the triggerHandler to the top of the drop event handler, after the variable declarations.  Since the triggerHandler returns a value, I assigned that value to a variable and if that variable is 1 then I continue with the changes in the DOM.

Is this way ok or I am missing something?

**Comment by dabeng** [comment]
Hi @achatzi78. I just published version 1.1.1 that provides option "dropCriteria" that could help users to limit the relationships between dragged node and drop zone. For more details, you could refer to http://dabeng.github.io/OrgChart/drag-drop/

**Comment by achatzi78** [comment]
Excellent addition, well done!

This is much better way than my hack.

**Comment by gazpachu** [comment]
@dabeng AFAIK, the dropcriteria only works to allow or deny the drop, but what if we want to cancel the drop once it happened?

I'm asking because I'm showing a modal dialog after the drop and I only want to accept the drop if the user click's on `accept`. If the user clicks on `cancel` then the drop wouldn't happen.

Thanks
