### ISSUE TITLE
Regarding node spacing

### ISSUE THREAD

**Issue by vijayperlakota** [dabeng/OrgChart#311]
Hi ,

I have a custom template node , it looks messy. Like most of the graph libs is there any possibility to give node spacing (space between two sibling nodes). I have not come across such options in this lib.

Much appreciated your help.

Thanks,
-VJCoder

**Comment by filip0v** [comment]
As an example:

```
tr.nodes > td {
    padding: 0 5px;
}
```

**Comment by vijayperlakota** [comment]
@filip0v Awesome the solution works perfectly. 💯  👍

**Comment by CaptainCannabis** [comment]
If i do this - the Diagramm wont fit in the wrap on page load
