### ISSUE TITLE
Init doesn't change data source correctly

### ISSUE THREAD

**Issue by TheMattyBoy** [dabeng/OrgChart#315]
Hi,

This is an awesome project, but I've hit a major problem in that the init command doesn't work correctly when changing the data source

If use init to load a new datasource like this

oc.init({ 'data': newDataSource});

Then the chart will udpate with the new data. However, if I then change some aspect of the chart again, such as the depth

oc.init({ 'depth': 4 });

The data from the old data source comes back!

This is repeatable in your reload-data.html example. e.g. If I change one of the button events to read

     oc.init({ 'data': data });
     oc.init({ 'depth': 4 });

Then when pressing the button, the chart changes to the new data source, but then flips back to the old data source.

In the example file you can see the effect on button 2 - I added a delay to make it obvious what's happening (need to rename as .html)

[reload-data init not working correctly.txt](https://github.com/dabeng/OrgChart/files/1522005/reload-data.init.not.working.correctly.txt)

**Comment by dabeng** [comment]
Hi @TheMattyBoy , thanks for giving so many details. I think you misunderstand the APIs.
1. if you want to change option after chart initiation, you should use method setOptions(). While this method is just available for setting option pan and zoom.
2. in your case, you have to use statement `oc.init({ 'data': data, 'depth': 4 })` 
3. under the hood, methid init will use the existing options to reinitialize orgchart

**Comment by TheMattyBoy** [comment]
Thanks for explaining dabeng, I've updated my code so the datasource is always provided when changing the depth, and that seems to have cured the issue. Many thanks!

**Comment by Mhmdasfak** [comment]
@dabeng  Iam Using init Method After Ajax DataSource And It is Not Working


this is the Code I am Using

$.mockjax({
      				url: '/orgchart/initdata1',
      				responseTime: 1000,
      				contentType: 'application/json',
      				responseText: org_chrt2
    });
				 var oc = $('#chart-container').orgchart({
	      				'data' : '/orgchart/initdata1',
	      				'depth': 3,
	      				'nodeContent': 'title',
						'exportButton': true,
	      				'exportFilename': 'MyOrgChart',
						'pan': false,
	      				'zoom': false
						
	    				});

				 oc.init({'data' : '/orgchart/initdata1'});
Here The org_chrt2 is Changing But The Chart Is Not Changing
