### ISSUE TITLE
<br> in nodeContent?

### ISSUE THREAD

**Issue by lordzpipo** [dabeng/OrgChart#32]
hi @dabeng,
after few week ago, i got another question,
can i know, nodeContent only support single line?

example:
`nodeContent: 'title';`
and 
`title:'a<br>b'`

it only show 
`a` ini chart...
if you need image support please let me know, thanks !

**Comment by dabeng** [comment]
Hi @lordzpipo . I did a testing. The result is shown as below:
![screenshot from 2016-06-29 09-38-31](https://cloud.githubusercontent.com/assets/5689075/16438332/70604b7c-3d74-11e6-91f6-c3a603b5befd.png)

What you need to do is just adjusting some css code. In fact, plugin orgchart allows users to embed html code snippets in json datasource.
