### ISSUE TITLE
Nodes alignement

### ISSUE THREAD

**Issue by atmacola** [dabeng/OrgChart#320]
There is an alignment problem when a node that contains only one child is next to a node that contains more than one child.

![selection_129](https://user-images.githubusercontent.com/7382872/33828491-a41475ac-de6c-11e7-9a7e-77f80138fcee.png)

This is explained by the absence of border-top in one case, which causes a gap of 2 px.
One possible solution would be to compensate for the size of the cell, in my example, by increasing the size of the font.

`.leftLine:not(.topLine) {
    font-size: 16px;
}`

![selection_130](https://user-images.githubusercontent.com/7382872/33828624-2389a8f2-de6d-11e7-96c4-c43d8e31035f.png)

**Comment by dabeng** [comment]
Hi @atmacola . Thanks a lot for your bug report. In fact, it's the same with #286.

I have fixed it in version 2.0.11. You can check the updated [demo](https://rawgit.com/dabeng/OrgChart/master/demo/edit-chart.html) without setting "font-size" :blush:

**Comment by atmacola** [comment]
Hi @dabeng . Thanks for your reply (and your nice work =). I didn't see any difference in the demo ?? but it look great in my project.

**Comment by dabeng** [comment]
Sorry @atmacola , you can try the [demo](https://codepen.io/dabeng/pen/xOxggw) on codepen.io to check the latest modification about node layout.

**Comment by dabeng** [comment]
<img width="914" alt="screen shot 2017-12-14 at 10 03 22 am" src="https://user-images.githubusercontent.com/5689075/33971962-50bb4da8-e0b6-11e7-85ea-d2fbaeecc5f9.png">

**Comment by atmacola** [comment]
Yes I saw, I am aware that a font size is not the best way to size a cell, I wanted to leave you the choice of the solution. Anyway thank you for your great plugin
