### ISSUE TITLE
Broken Drag'n Drop

### ISSUE THREAD

**Issue by atmacola** [dabeng/OrgChart#322]
Since the last update, the drag and drop is broken. On Firefox, it is no longer possible to move the nodes, and on chrome, the lines do not fall on the elements.

[demo](https://rawgit.com/dabeng/OrgChart/master/demo/drag-drop.html)
Move "Li Xin" on "Su Miao"

![selection_131](https://user-images.githubusercontent.com/7382872/33982838-59990234-e0b2-11e7-9941-04fc06b471e1.png)

**Comment by dabeng** [comment]
Sorry @atmacola , It's my mistake. I have fix it in new version 2.0.12.

Beside, It seems that e2e tests should be added as soon as possible.

**Comment by atmacola** [comment]
On chrome it works well now, but on Firefox (version 57.0), it is still impossible to move the nodes

**Comment by costonb** [comment]
This definitely does not work in Firefox still.  We ran across it in some testing and then tried your drag and drop example and it didn't work in Firefox either.
