### ISSUE TITLE
Allow 0 for rootNode id

### ISSUE THREAD

**Issue by nykewl** [dabeng/OrgChart#327]
In order for getHierarchy() to work, every node needs an Id - however, setting the rootNode to zero throws an error.

**Comment by dabeng** [comment]
Hi @nykewl , feel free to play around the updated [getHierarchy() demo](https://codepen.io/dabeng/pen/BJzPBw) and set some node id to 0.

**Comment by nykewl** [comment]
Thanks. The demo works
I am using a dynamic JSON data source and it does not work if the id is the number 0. I have to convert it to string (which is fine).
