### ISSUE TITLE
bug in draw report path + ajax

### ISSUE THREAD

**Issue by hadihashem** [dabeng/OrgChart#338]
[report-path.html.txt](https://github.com/dabeng/OrgChart/files/1646744/report-path.html.txt)
Hello
When using ajax datasource in draw report path, the textbox in edit panel is not updated on node selection
This bug doesn't show when using a string data source
Please advise
Kind regards

**Comment by dabeng** [comment]
Hi @hadihashem , the issue you mentioned is due to the following code snippets:
```js
    oc.$chart.find('.node').on('click', function() {
      $('#selected-node').val($(this).children('.title').text());
    });
```
In your case, you should replace the above lines with the following lines:
```js
    $('#chart-container').on('click', '.node', function(event) {
      $('#selected-node').val($(event.target).children('.title').text());
    });
```

**Comment by hadihashem** [comment]
Hi @dabeng 
Thank you for your feedback but unfortunately it does work using this change
Please advise
Kind regards

**Comment by dabeng** [comment]
Sorry @hadihashem , I did a mistake, we should use `event.currentTarget`.
```js
    $('#chart-container').on('click', '.node', function(event) {
      $('#selected-node').val($(event.currentTarget).children('.title').text());
    });
```
Please check this [Demo](https://codepen.io/dabeng/pen/LeqBmV) :blush:

**Comment by hadihashem** [comment]
It works mutch better
Thank you
Regards
