### ISSUE TITLE
Vertical level drag and drop functionality

### ISSUE THREAD

**Issue by jozellrili** [dabeng/OrgChart#347]
Hello,

I'm using this plugin in one of my projects and I'm trying to add a drop and drag functionality on vertical level org chart. I was successful incorporating the functionality but the styles and position of the nodes is not right. FYI, I've got hundreds of people in the org chart so having to drag and drop them on a location within a horizontal chart is clearly a headache for the user.

Are you planning to add this support on the org chart?

TIA

**Comment by Dhirendra-bishtdev** [comment]
I am also facing the same  issue, the drag and drop not behaving properly,

**Comment by Surjitsinght** [comment]
facing the same issue.

Have you find any solution for the same?

**Comment by jozellrili** [comment]
@phpdev-expert @Surjitsinght Sad to say that the org chart team does not responded and seems like they don't have any plans on supporting this feature. Our team make some modification to the plugin just to make the vertical drag possible. Which I strictly do not recommend.

**Comment by Surjitsinght** [comment]
@jozellrili Thanks for your reply.

I am trying a solution to refresh the organization chart when the node is dropped(nodedrop.orgchart) and it is working fine for the first instance.

but when i dragged the node for the second time (nodedrop.orgchart) event not fired.

I think when we update the datasource of the orgchart using init method all the other events (nodedrop.orgchart etc.) stops firing.

Any solution for the same?

Please Help

**Comment by dabeng** [comment]
Hi @jozellrili @phpdev-expert @Surjitsinght From the version 3.4.0, you can drag&drop in the hybrid(horizontal + vertical) chart with the help of [JSONDigger](https://github.com/dabeng/json-digger) utility class. I have created the [Demo](https://codepen.io/dabeng/pen/yLqQGRb) on codepen.io for you.
