### ISSUE TITLE
Jquery version 3.2.1

### ISSUE THREAD

**Issue by JeanCarriere** [dabeng/OrgChart#348]
The jquery version is set to approximately equivalebt to 3.2.1
COuld it be possible to set it to compatible with version 3.2.1 ("^3.2.1) otherwise npm builds the package with 2 different jquery versions : the latest 3.3.1 and the previous one 3.2.1.

**Comment by dabeng** [comment]
Hi @JeanCarriere , thank you very much. I have changed jquery dependency to ^3.2.1 in new released version 2.1.1.
