### ISSUE TITLE
The min.js is 3x larger than the regular .js

### ISSUE THREAD

**Issue by warrenspe** [dabeng/OrgChart#349]
I'm not sure how this could have happened, but
https://github.com/dabeng/OrgChart/blob/master/dist/js/jquery.orgchart.min.js
is 157KB, while
https://github.com/dabeng/OrgChart/blob/master/dist/js/jquery.orgchart.js
is 58.6KB

**Comment by dabeng** [comment]
Hi @warrenspe , thank you very much for your good advice. I have released new version 2.1.1. From this version, I will generate external source map file for jquery.orgchart.min.js.
