### ISSUE TITLE
Make the chart-container scrollable

### ISSUE THREAD

**Issue by Brittediedritte** [dabeng/OrgChart#354]
Hello!

Is there a way to make the chart-container scrollable?

Thanks!

**Comment by scrobbleme** [comment]
@Brittediedritte Can you please describe this a little more?

**Comment by Brittediedritte** [comment]
Thank you. I just solved the problem. 
The div "chart-container" has the css property overflow=auto. I changed it to 'scroll' in style.css, but no scrollbar appears, because the overflow property is overwritten by orgchart.css.
Now, I set the property to 'scroll' with javaScript, after chart is initialized.
