### ISSUE TITLE
More than one classname

### ISSUE THREAD

**Issue by Brittediedritte** [dabeng/OrgChart#356]
Hello!

I need to set the slide-up classname, because I want to hide nodes by default. I also want to have colored nodes, so I added some custom classes,
Is it possible to add two classnames to a node?

Thanks, Britta

**Comment by warrenspe** [comment]
Not the owner; but try adding them space-delimited; ie
`className: "slide-up something-else"`

**Comment by Brittediedritte** [comment]
Thanks! I just tried the css notation, but it does not work.

**Comment by warrenspe** [comment]
How are you initializing the orgchart? (Or, what sort of data are you passing to it?)  I am using AJAX, and have verified that adding `"className": "my-first my-second"` to each of the returned nodes does add the CSS classes to the created node in the OrgChart

**Comment by Brittediedritte** [comment]
The nodes aren`t displayed, if I pass the css classes like this:
For example:
{"id": "<b>Sales / Europe</b><hr><hr>",  "name":"ES-EU",  "title":"Max Mustermann",  "className":"slide-up levelTwo", "collapsed": true}

Initializing, please ignore the backslashes:
var oc = $('#chart-container').orgchart({'data' : datascource,
'nodeContent': 'title',
'initCompleted': function ($chart) {
var $container = $('#chart-container');
$container.scrollLeft(($container[0].scrollWidth - $container.width())/2);},
'nodeID': 'id',
'createNode': function($node, data) {
var secondMenuIcon = $('<i>', {
'class': 'fa fa-info-circle second-menu-icon',
click: function() {
	$(this).siblings('.second-menu').toggle();
}});
var secondMenu = '<div class=\"second-menu\"><span class=\"avatar\">' + data.id + '</span></div>';
$node.append(secondMenuIcon).append(secondMenu);
},
'pan': true,
'zoom': true
});
document.getElementById('loader').style.display = "none";
document.getElementById('chart-container').style.overflow = "scroll";
 $('#btn_expand').on('click', function() {
      var $temp = oc.$chart.find('.hidden').removeClass('hidden');
      $temp[0].offsetWidth;
      $temp.find('.slide-up').removeClass('slide-up');
var $container = $('#chart-container');
$container.scrollLeft(($container[0].scrollWidth - $container.width())/2);
    });
    
    $('#btn_collapse').on('click', function() {
      oc.hideChildren(oc.$chart.find('.node:first'));
var $container = $('#chart-container');
$container.scrollLeft(($container[0].scrollWidth - $container.width())/2);
    });
}
);(jQuery);

CSS for node colors: (I did not change the slide-up class)

.orgchart { background: #fff; }
.orgchart td.left, .orgchart td.right, .orgchart td.top { border-color: #aaa; }
.orgchart td>.down { background-color: #aaa; }
.orgchart .levelOne .title { background-color: #006699; }
.orgchart .levelOne .content { border-color: #006699; }
.orgchart .levelTwo .title { background-color: #009933; }
.orgchart .levelTwo .content { border-color: #009933; }

**Comment by Brittediedritte** [comment]
I have just realized, that the nodes aren`t displayed, too, if I just pass the slide-up class, without the custom class

**Comment by Brittediedritte** [comment]
I get it. The Expand button causes the problem
