### ISSUE TITLE
Patch for jquery.orgcharts.css - Lines are not shown correct when 'float' is set by another CSS

### ISSUE THREAD

**Issue by keebeegee** [dabeng/OrgChart#36]
Example: 

Current: 
.orgchart td.left {
  border-left: 1px solid rgba(217, 83, 79, 0.8);
}

New: 
.orgchart td.left {
  border-left: 1px solid rgba(217, 83, 79, 0.8);
  float: none;
}

If 'float' for a "td" is be set by another css, lines will not shown correctly.   

You can reproduce the error by simply adding style:

.left {
    float: left;
}

to the page. 

cheers 
kbg

**Comment by dabeng** [comment]
Wow, great! Thanks a lot. I'm gonna to try it out and then introduce this helpful code snippet.

**Comment by dabeng** [comment]
Hi @keebeegee , I haved fixed this bug in jquery.orgchart.css file and release new version. Thank you very much :blush:
