### ISSUE TITLE
function that return the full data

### ISSUE THREAD

**Issue by cyber-m** [dabeng/OrgChart#37]
Hello,
the getHierarchy($chart) return me somthing like this:
`{
  "id": "01",
  "children": [
    {
      "id": "02"
    },
    {
      "id": "03"
    },
    {
      "id": "04"
    }
  ]
}`

but I want to get the full data with the name and relationship:

`'name': 'Ball game',
          'relationship': '001',
          'id':'01',
          'children': [
              { 'name': 'Football', 'relationship': '110','id':'02' },
              { 'name': 'Basketball', 'relationship': '110' ,'id':'03'},
              { 'name': 'Volleyball', 'relationship': '110' ,'id':'04'}
          ]`

is there a function that return JSON data like the above?

my main goal is to save that data into variable after I edit the chart so when I load it again all changes I made will be remained.

I'll appreciate any help on the matter

**Comment by dabeng** [comment]
OK, I'll think about this demand seriously.

**Comment by dabeng** [comment]
After careful thought, I believe that the getHierarchy() method is just what you need, and in fact, this method is desiged to fulfill the demand you described above. Specifically, you could read latest datasource through the node IDs according to the result from getHierarchy() and then send it to backend for updating action.

**Comment by cyber-m** [comment]
Thank's a lot for your reply, I took your advice and what I end up doing is the following :
getHierarchy > recursively iterate over the object return by getHierarchy and adding properties to it > convert to JSON string using JSON.stringify()

I think that it will be a good idea to add to an example to the examples folder on how to get the "full data" after getting the object from getHierarchy
