### ISSUE TITLE
Duplicate After Open Twice

### ISSUE THREAD

**Issue by erb4f1dotama** [dabeng/OrgChart#373]
When i first open my page, so far so good. But when i back to previous page than go to orgchart page, the chart duplicated.
![screenshot_2018-04-18_11-41-55](https://user-images.githubusercontent.com/34017687/38912370-0dd0f47e-42ff-11e8-9679-73fcbaa9b01c.png)
![screenshot_2018-04-18_11-42-08](https://user-images.githubusercontent.com/34017687/38912371-0e3de30e-42ff-11e8-8ac5-121d462e40b1.png)

This my simple code:
viewer.js
`import { HierarchyViewer } from 'components/HierarchyViewer/Loadable';

export class OrganizationHierarchyViewer extends React.Component {
return(
<HierarchyViewer
   dataSource={dataViewer}
/>
)}`

And this link for jquery.orgchart,js
https://jsfiddle.net/g4ftsxh8/
[https://jsfiddle.net/g4ftsxh8/](url)

**Comment by marioscialpi** [comment]
Did you find a solution? I have similar issue.
Thanks

**Comment by erbaafidotama** [comment]
use this code:
$('#chart-container').empty();

for empty your container. then create new chart

**Comment by erb4f1dotama** [comment]
use this code:
$('#chart-container').empty();

for empty your container. then create new chart
