### ISSUE TITLE
html2canvas is not defined when export [SOLVED]

### ISSUE THREAD

**Issue by erb4f1dotama** [dabeng/OrgChart#391]
I try to export orgChart to pdf or png. But, when i click the button export, always error.

Uncaught ReferenceError: html2canvas is not defined

Can help me to solving this problem??

**Comment by erb4f1dotama** [comment]
I have try  to import html2canvas in my js file.

import './jquery.orgchart.js';
import './html2canvas.min.js';
import { html2canvas } from 'html2canvas';

if ($('#chart-container').length > 0) {
      if ($('#chart-container').children().hasClass('orgchart')) {
        $('#chart-container').empty();
      }
      $('#chart-container').orgchart({
        data: this.props.dataSource,
        menu: this.generateMenuDetail(),
        exportButton: true,
        exportFilename: 'OrgChart',
        exportFileextension: 'png',
      });
    }
  }

return (
      <div>
        <Helmet>
          <title></title>
          <meta name="description" content="Description of HierarchyViewer" />
        </Helmet>
        <div className="container">
          <div id="chart-container"></div>
          <script type="text/javascript" src="./html2canvas.min.js"></script>
        </div>
      </div>
    );

**Comment by guifeliper** [comment]
Hey, how are you? 
Actually, you need the https://rawgit.com/dabeng/OrgChart/master/demo/js/jspdf.min.js, so I advise you to give it a try on the main HTML, it worked for me, and then you see where is the best place to insert it.

**Comment by erb4f1dotama** [comment]
Thank for help.
Should I install "npm install jspdf"? Or just copy code from that url?

**Comment by guifeliper** [comment]
I am using like this on the main file, I am not using the npm install.     
<script src="https://rawgit.com/dabeng/OrgChart/master/demo/js/jspdf.min.js"></script>

**Comment by cumibulat** [comment]
thanks @guifeliper to throwing some pointer.. 
i can use tag script to import jspdf or like this :

    import jsPDF from './jspdf.min.js';
    import html2canvas from './html2canvas.min.js';
    window.html2canvas = html2canvas;

**Comment by erb4f1dotama** [comment]
Thanks @cumibulat ...
