### ISSUE TITLE
Disturbing Colors when Export to PNG / JPEG

### ISSUE THREAD

**Issue by erb4f1dotama** [dabeng/OrgChart#406]
![harpa-orgchart 4 blur](https://user-images.githubusercontent.com/34017687/42857861-f3fb4874-8a75-11e8-937f-35e42929d859.png)
 
How to clear pink color??
Thanks for help and respond.

**Comment by chrisjianghp** [comment]
Faced the same issue, including pdf and png.
Have you resolved it?

**Comment by dabeng** [comment]
Hi @erb4f1dotama @chrisjianghp You need to use new background to override existing background setting. For example:
```css
 .orgchart { background: #fff; }
```

**Comment by chrisjianghp** [comment]
It works, thanks.

**Comment by erb4f1dotama** [comment]
Wow, thanks. It works
