### ISSUE TITLE
stracure data like this

### ISSUE THREAD

**Issue by vahidalvandi** [dabeng/OrgChart#41]
very thanks for orgchart , do it work in bellow structure data  ??
 
```
 { id: '1', parent: '' },
 { id: '2', parent: '1' },
 { id: '3', parent: '1' },
 { id: '4', parent: '2' },
 { id: '5', parent: '3' },
```

**Comment by dabeng** [comment]
Hi @vahidalvandi , first of all, thanks for your proposal. Frankly, I don't believe the above format(similar to traditional tree-like table schema in RDBMS) of datasource is an feasible alternative. Imagine that every time the internal login of orgchart plugin reads a new node data, it has to append new child node and change the link-lines, it's too expensive. Besides, once there is an incorrect "parent" attribute, it‘s likely to result in the breakdown of orgchart construction.
