### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by paulrisk3** [dabeng/OrgChart#411]
Hello. I am sure that I've simply missed something, but I'm having a terrible time starting my first orgchart. Could the documentation be more complete, or is there somewhere else I ought to look? I've installed orgchart with npm, and then tried the code from the first example in this site: https://codepen.io/dabeng/post/orgchart . Nothing shows up in my code when I put that in <script> tags in an HTML document.

**Comment by erb4f1dotama** [comment]
Are you using reactJs?
I downloaded source code form this repo, then i import jquery.orgchart.js.

Sorry for my bad english.

**Comment by paulrisk3** [comment]
Ah, I think it was that import that I was missing. Thanks!
