### ISSUE TITLE
Custom Template not working on IE

### ISSUE THREAD

**Issue by hadihashem** [dabeng/OrgChart#415]
Hi @dabeng 

The feature of Custom Template is not working on IE
Your demo file "custom-template.html" is a good example

[custom-template.html.txt](https://github.com/dabeng/OrgChart/files/2241037/custom-template.html.txt)

I'm using IE11
I noticed the same problem with Edge on both Win 8.1 and Win 10

Regards

**Comment by dolphinfine** [comment]
"template strings" in prior editions of the ES2015 specification is not support by ie directly

**Comment by hadihashem** [comment]
Hi @dabeng 
Do you know any solution?
Regards

**Comment by dabeng** [comment]
```js
   var nodeTemplate = function(data) {
      return `
        <span class="office">${data.office}</span>
        <div class="title">${data.name}</div>
        <div class="content">${data.title}</div>
      `;
    }
```

Hi @hadihashem . You can replace the above code snippet with the following code snippet:
```js
    var nodeTemplate = function(data) {
      return '<span class="office">' + data.office + '</span>' +
        '<div class="title">' + data.name + '</div>' +
        '<div class="content">' + data.title + '</div>';
    };
```
Feel free to play around with the following demos on codepen.io:
[node template based on es6 template string](https://codepen.io/dabeng/pen/jabjWK)
[node template based on html string](https://codepen.io/dabeng/pen/QVGgMz)
[](url)

**Comment by hadihashem** [comment]
works good
thank you
