### ISSUE TITLE
On click event

### ISSUE THREAD

**Issue by vhaxha** [dabeng/OrgChart#416]
1. Is it possible to have On click event (to click on node and then to display information with alert()).

2. Also is it possible to use with Angular 6, to add checkbox and to display Node Element vs Time History.

Do you have a simple example for the task above.

Thank you.

**Comment by dabeng** [comment]
Hi @vhaxha . As for question 1, I have created a demo([read node info on clicking node](https://codepen.io/dabeng/pen/gjqvmq)) for you, feel free to play around with it and tell me whether or not it covers your demand.

**Comment by vhaxha** [comment]
Hi Xuebin,


This is exactly what we were looking for.

Thank you very much for your time and help.



Kind regards,

Vesel Haxha


________________________________

**Comment by vhaxha** [comment]
Hi Xuebin,


Thank you very much for your time and help.


Kind regards,

Vesel Haxha


________________________________

**Comment by efleon9** [comment]
Hi!

I'm using data structure based on ul & li tags.

I want pass data (data-id) from li tag to orgchart.

`<li data-id="1"> Title Node </li>`

How could is possible?
