### ISSUE TITLE
set toggleSiblingsResp to false, left/right arrows still show and affect

### ISSUE THREAD

**Issue by firstrose** [dabeng/OrgChart#418]
Whatever toggleSiblingsResp is true or false, left/right arrows always appear and toggle siblings.

按照文档，toggleSiblingsResp貌似是控制是否允许toggle兄弟节点，但是即使把这个参数设为false，节点两边还是有左右箭头，点击还是会toggle.

**Comment by dabeng** [comment]
Hi @firstrose . 首先感谢你使用orgchart plugin :blush: 
关于你的问题，是这样。默认情况下，点击水平方向的箭头时，会展开或折叠水平方向上的所有兄弟节点。toggleSiblingsResp这个option如果被设置为true时，点击某节点右侧的箭头，会展开或折叠其右边的兄弟节点，同理，点击其左侧的箭头，会展开或折叠它左边的兄弟节点。此外，这个option的默认值是false，意思就是说单击水平的箭头，是同时展开或折叠两边的兄弟节点的。希望我把自己的想法说明了 :blush:

**Comment by firstrose** [comment]
谢谢你的说明。请教一下，有没有办法禁止展开或折叠两边的兄弟节点呢？我只需要展开/折叠子节点，兄弟节点的toggle反而会引起用户的误解。

**Comment by dabeng** [comment]
Hi @firstrose 你可以参考这里https://github.com/dabeng/OrgChart#tips
`How can I deactivate expand/collapse feature of orgchart?`

**Comment by firstrose** [comment]
谢谢，这个办法确实有效。不过我想建议你加个选项，分别控制四周的箭头是否启用，而不是用这种类似于hack的办法。另外，在试验的过程中我发现一个问题。如果只禁用了左右箭头，但是没有同时禁用上方箭头的话，一旦不慎将树收缩到某个子节点，该节点的各父代节点的兄弟节点将永久隐藏。这不大符合一般人的预期。我的意思是，例如ajax-datasource.html的树，如果全树收缩到Hei Hei，那么从Hei Hei展开Su Miao后，至少应该能够通过点击Su Miao下面的箭头，先隐藏Hei Hei，再展开Su Miao的所有2个子节点。但是实际上Tie Hua无法再展开。

**Comment by dabeng** [comment]
因为长期听到来自用户的声音是，他们对展开/折叠按钮的需求是有时需要启用，有时需要停掉，并不绝对，所以默认生成展开/折叠按钮，只是根据用户具体需求，用CSS去控制启用关闭状态，应该是较为便捷的方案。

**Comment by firstrose** [comment]
好的，谢谢

**Comment by tedcattw** [comment]
您好,
我想追問作者一下  關於 問題
Aug 14, 2018 firstrose 谢谢你的说明。请教一下，有没有办法禁止展开或折叠两边的兄弟节点呢？我只需要展开/折叠子节点，兄弟节点的toggle反而会引起用户的误解。

作者您的回覆似乎跟原問題不同, 原問題是希望您能夠開發出選項, 能夠設置長樹/個別節點的時候, 不要出現左邊或右邊的折疊展開箭頭, 或者  上/下 的箭頭
所以不會有您所謂的"永遠" 困擾

**Comment by tedcattw** [comment]
或者說, 那麼如果我現在想用hack的方式移除特定節點/或者是整棵樹的  "左右上"摺疊功能,  只保留常見的 "下"(摺疊其下所有樹) 這個功能, 
請問一下應該要使用什麼語法可以達到這個效果呢?

謝謝
