### ISSUE TITLE
请教，有快捷的办法可以调整同一个level的节点的高度相同吗？

### ISSUE THREAD

**Issue by chrisjianghp** [dabeng/OrgChart#419]
感谢 @dabeng 做了这么好的组织架构图。
请帮忙看下以下问题：
因为数据差异较大，同一个level的节点高度差异也很大，如图。
有没有什么快捷的办法，让同一level的节点高度相同？或者同一个图的节点高度相同也可以？
注:因为使用了AJAX, 可能需要动态调节。谢谢。
期待您的回复。

![orgchart](https://user-images.githubusercontent.com/33885188/44080288-2f701380-9fde-11e8-9fd7-2fbebd7ec023.png)

**Comment by dabeng** [comment]
Hi @chrisjianghp 感谢使用orgchart plugin :blush: 
关于你的需求，换作是我，可能会从以下几个方面入手：
1. 组织结构图，其实核心作用是借助树状结构展示给用户直观的层级关系。所以整齐的节点布局对整体的展示效果影响很大。除非情况极为特殊，否则不建议出现大大小小，高高低低的节点。
2. 在保证节点尺寸相同后，如果有额外信息需展示，那么可以加次级菜单进去，用户需触发相应的功能按钮，额外的信息才会以tooltip, popover, dialog的形式展现出来。

**Comment by chrisjianghp** [comment]
@dabeng 好的，谢谢。
