### ISSUE TITLE
EXPORT

### ISSUE THREAD

**Issue by arucastillo** [dabeng/OrgChart#424]
Hello

When i try to download my orgchart, it work but incompleted

![estaaaaaa](https://user-images.githubusercontent.com/36679993/46109371-9cd48600-c19d-11e8-9dd7-1a63f72eab72.png)

Can someone help me with this

**Comment by dabeng** [comment]
Hi @arucastillo, could you share a demo(codepen.io, jsfiddle) link ?

**Comment by dabeng** [comment]
Hi @arucastillo  I got a complete exported picture of orgchart on Chrome. What is the browser when you came across the above issue ?

**Comment by arucastillo** [comment]
I think is a css problem, because when I delete the line `display:inline-block` is give the org chart incomplete

**Comment by arucastillo** [comment]
I managed to solve the problem

thx

**Comment by dabeng** [comment]
Congratulations :blush:

**Comment by LucasLiu-Stantec** [comment]
#chart-container {
        display: inline-block;
    }
Confirmed, I just fixed the same issue with this css fix. Thanks guys.
