### ISSUE TITLE
ie11+? could support ie9+?

### ISSUE THREAD

**Issue by design365** [dabeng/OrgChart#43]
how?

**Comment by dabeng** [comment]
Sorry @design365 , because the main behavior of orgchart plugin is based on CSS3 transforms and transitions, through my testing, I can support IE 10+ but not IE9

**Comment by burock7** [comment]
I have a problem with IE11, it's working fine with Firefox and Chrome but I've got below error message while in IE11 and charts were not displayed, even on your github demo page. Do you have any idea about how can I fix this?
![image](https://user-images.githubusercontent.com/28536163/48066100-5844fd00-e1d5-11e8-93a2-cab90e38aac1.png)
