### ISSUE TITLE
box shadow on nodes

### ISSUE THREAD

**Issue by CaptainCannabis** [dabeng/OrgChart#446]
i want to use a box shadow on the nodes. therefore i have to remove the transparent border and the padding. This leads to nodes without spacing. To achieve a spacing i tried to move the padding to the "td". But this way the witdh of the chart is not calculated right and it will overflow the wrap without beeing zoomed.
Any suggestions?

**Comment by emirlike** [comment]
In 2022, you can simply:

```
	.orgchart .node {
		filter: drop-shadow(3px 3px 4px #a7a7a7)
	}
```
