### ISSUE TITLE
Aligning Children Vertical

### ISSUE THREAD

**Issue by mfahadi** [dabeng/OrgChart#46]
Hi, I have used OrgChart library for a complex chart and works great. Kudos for the great work :). 

But when chart gets bigger it becomes useless pretty soon, because of horizontal display of children. I could not find an option in plugin to align children vertical, under the parent. 

Please see the attached image, I don't want the connecting lines for children, just alignment will fulfill my requirements. 

If there is no option currently in the library, can you please guide me on how can I modify the library to achieve the effect. Thanks.
![chart](https://cloud.githubusercontent.com/assets/16061204/17594575/43c5e246-6003-11e6-80a4-b2a86463695f.png)

**Comment by dabeng** [comment]
It's a constructive proposal. I need some time to think about a temporary solution or to expose a new option.

**Comment by dabeng** [comment]
From version 1.2.0, users never have to worry about how to align a huge of nodes in one screen of browser. The option "verticalDepth" allows users to align child nodes vertically from the given depth.
![snapshot](https://cloud.githubusercontent.com/assets/5689075/18310609/0325a33a-74c5-11e6-806c-5d8fcde1298f.png)
