### ISSUE TITLE
大神好，请问有没有多个节点汇聚成一个节点的方法？谢谢！

### ISSUE THREAD

**Issue by No54** [dabeng/OrgChart#486]
![orgChart](https://user-images.githubusercontent.com/38535403/58858799-fd2ba800-86da-11e9-94a6-3fad8b78921e.png)

**Comment by dabeng** [comment]
@No54 ，你的问题是点击何处，合并哪些节点啊？就这一个图，没太看懂

**Comment by No54** [comment]
感谢您回复，不好意思，我没描述清楚。就是是只能生成树形结构吗？如果是多个节点汇成一个节点可以吗？就不是树了，变成图了。

**Comment by dabeng** [comment]
抱歉，如果你在浏览器的控制台简单扫一下html代码就会发现，这个组件的基本实现原理就是用嵌套的table结构来模拟组织结构图，节点就是td，节点间的连线就是td 的border。所以节点间的任意连线，对这个组件来说是无法实现的。如果你有“任意连线”这方面的需求，建议你使用D3.js C3.js 😊

**Comment by No54** [comment]
嗯嗯，了解了，谢谢您。就是觉得您的这个repo很漂亮，所以想试试😄
