### ISSUE TITLE
完全隐藏上下左右箭头

### ISSUE THREAD

**Issue by Tzns** [dabeng/OrgChart#488]
dabeng你好，我的客户需求是节点都较小，客户点击的时候很容易就误操作，所以我希望完全隐藏上下左右箭头。

**Comment by dabeng** [comment]
$('.orgchart').addClass('noncollapsable');

**Comment by dabeng** [comment]
附带的问题是，增加领这个class，就无法开到默认的展开折叠按钮了

**Comment by Tzns** [comment]
确实有效，谢谢dabeng

**Comment by TownTowner** [comment]
> $('.orgchart').addClass('noncollapsable');

可以把这个加入到选项功能吗？包裹到组件中，不然还要后序处理。
