### ISSUE TITLE
can please help me to write angular directive for Org Chart

### ISSUE THREAD

**Issue by SUVADEEP** [dabeng/OrgChart#49]
can you please help me to write angular directive for Org Chart

**Comment by dabeng** [comment]
To be honest I am not optimistic about AngularJS. While, if you really need directive of OrgChart, you can refer to **Directive** section of [Learn AngularJS with example](https://github.com/dabeng/learn-angularjs-with-example)

**Comment by chenxu7601257** [comment]
Would much appreicate if you could provide the angularJS orgChart, thanks.
