### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by fvlima** [dabeng/OrgChart#5]
It's possible to set the orgchart orientation? I need to put it in the horizontal orientation, instead of the vertical default orientation. I don't found anything about that in the docs, then I'm asking here.

**Comment by dabeng** [comment]
Currently, default orientation is vertical, I'm planning to add an particular option which is used to control the orientation for orgchart. This option will be available in orgchart v 1.0 :)

**Comment by fvlima** [comment]
By the way, I forgot to commend your project. It's awsome. Congratulations for this work.

**Comment by badulesia** [comment]
Hello.
Very interesting and nicely done plugin. It is usefull for my php project.
I have a request which fits this "orientation" issue : the organization is vertical, from top to bottom. I have the need of a bottom to top organization, to display a tree of life.
Would you mind thinking about this ?

Thanks a lot.

**Comment by dabeng** [comment]
Hi badulesia, could you show me a sketch to show your demand?

**Comment by badulesia** [comment]
Le 26/04/2016 à 06:35, dabeng a écrit :
> Hi badulesia, could you show me a sketch to show your demand?
>
Hi.
It's simple : reverse upside down the organization, with general manager 
at bottom. Here is a "what I need" example joined.

It will allow making chart looking like a tree of life, such as this one
http://www.talkorigins.org/faqs/comdesc/images/phylo.gif
I don't need charts such complicated as this gif example, and your 
plugin suits me, but it needs to be with root at bottom.

Thank you :)

**Comment by dabeng** [comment]
Hi guys. Time flys. According to your demands, I add an option "direction" designed to help users arrange orgchart nodes in different orientations. You can find it on version 1.0.1.

**Comment by badulesia** [comment]
Le 07/05/2016 à 14:02, dabeng a écrit :
> Hi guys. Time flys. According to your demands, I add an option
> "direction" designed to help users arrange orgchart nodes in different
> orientations. You can find it on version 1.0.1.
>
Hello.
Wonderfull ! I will use it to build a "tree of life" sketch.
I'll send you a picture when it is done :)
Thank you for your reactivity.

B.

**Comment by dabeng** [comment]
Wish you success! :blush:
