### ISSUE TITLE
Edit chart does not work with the latest jQuery

### ISSUE THREAD

**Issue by danielekbom** [dabeng/OrgChart#50]
Several issues when using the latest jQuery (3.1.4) and the edit chart functionalities.
For example when adding a sibling the chart gets messed up.

I changed to the latest 2.x jQuery (2.2.4) and now everything seems to be working fine,

**Comment by dabeng** [comment]
Thanks a lot. It seems that I should upgrade jquery vesion in OrgChart

**Comment by dabeng** [comment]
In version 1.1.5, plugin orgchart can work well with latest jquery. Some inner functions of orgchart has been updated according to jquery 3.1.0
