### ISSUE TITLE
Can I add multiple levels of nodes using addChildren ?

### ISSUE THREAD

**Issue by killyoubilly** [dabeng/OrgChart#51]
Hi, I found document says that the data format in addChildren is json object,  but it seems that I can only add an array of node to next level or siblings.

Can I add multiple levels of nodes by calling addChildren once?
Or I need to redraw the chart to refresh it?

Thanks.

**Comment by dabeng** [comment]
Hi @killyoubilly , of course, you can. Here I just give you a sample code, you can run the following code snippets  in the console of [edit-chart](http://dabeng.github.io/OrgChart/edit-orgchart/) demo page then you will get two levels of nodes by calling addChildren() method only once.
```js
$('#chart-container').orgchart('addChildren'
  ,$('.node').eq(1)
  ,{'children': [{'name': 'Europe', 'relationship': '101', 'children': [{'name': 'A.C. Milan', 'relationship': '100'}]}]}
  ,$.extend({}, $('#chart-container').find('.orgchart').data('options'))
);
```

**Comment by killyoubilly** [comment]
Thank you for the data format.
Now I can add nodes once without recursive function.

**Comment by killyoubilly** [comment]
I found that the problem is the depth option in demo page.
It works after I remove it.
