### ISSUE TITLE
FONT NOT SHOWING

### ISSUE THREAD

**Issue by k3youmin** [dabeng/OrgChart#514]
![image](https://user-images.githubusercontent.com/15870174/64919990-ad35a480-d7e4-11e9-9b16-5134628c9426.png)

![image](https://user-images.githubusercontent.com/15870174/64919995-bde61a80-d7e4-11e9-9b58-849f8f28b349.png)

**Comment by dabeng** [comment]
Hi @k3youmin Maybe you can find solution in here - https://stackoverflow.com/questions/14366158/font-awesome-not-working-icons-showing-as-squares
