### ISSUE TITLE
why my browser(IE 11) can not show some special effect?

### ISSUE THREAD

**Issue by zylgujiguji** [dabeng/OrgChart#52]
Thanks for your great work about Jorgchart. But with using this plugin ,the result of mine is not so good.When I move the mouse into  a node, some special effect can not come out.The following is a comparison chart . In my result, the sign "up"、“down”、“right”、“left” can not come  out.
![example of your demo](https://cloud.githubusercontent.com/assets/21231867/17959275/ecaa1c46-6ad1-11e6-858a-e0e66a4f7949.png) the right one 
![the result of mine](https://cloud.githubusercontent.com/assets/21231867/17959278/eeb344a4-6ad1-11e6-956d-e240b73beac0.png) the wrong one

**Comment by zylgujiguji** [comment]
I have solved this problem。Sorry to interrupt you！

**Comment by dabeng** [comment]
I'm very glad that you wanna introduce OrgChart into your web application. I guess that maybe you forgot to reference  fontawesome.css file and got the above issue. Hope plugin OrgChart is your good helper.
