### ISSUE TITLE
Dist folder not available

### ISSUE THREAD

**Issue by shankaryadavy9** [dabeng/OrgChart#521]
Hi,
So far it was working fine but now suddenly i am getting below error while building using Angular 8.

An unhandled exception occurred: ENOENT: no such file or directory, open '../node_modules/orgchart/dist/js/jquery.orgchart.js'

I am using below npm version

    "orgchart": "^2.1.2",

**Comment by dabeng** [comment]
sorry @shankaryadavy9 I made a mistake when I updated .gitignore file. This bug has been fixed in new version 2.1.9.

**Comment by shankaryadavy9** [comment]
Thanks dabeng.
