### ISSUE TITLE
Rawgit shutdown - Demos no longer working

### ISSUE THREAD

**Issue by petrvecera** [dabeng/OrgChart#527]
The demos are loading CSS using raw git, which has been shutdown https://rawgit.com

The demos are no longer working
https://rawgit.com/dabeng/OrgChart/master/demo/right2left.html

![image](https://user-images.githubusercontent.com/8086995/67277548-54ce8280-f4c7-11e9-9ae3-2778bc88f8af.png)

**Comment by dabeng** [comment]
Thanks a lot for your reminding @petrvecera  😊 I have moved all demos to gh-pages. This is the working version https://dabeng.github.io/OrgChart/right2left.html
