### ISSUE TITLE
Hybrid kinda breaks everything

### ISSUE THREAD

**Issue by CatalinRadoi** [dabeng/OrgChart#528]
Hi! Great orgchart, I love it and I use it, but the hybrid mode (e.g. verticalLevel = 4, visibleLevel = 4) seems to break everything.

- loopChart doesn't work (it cannot read the "id"
- drag and drop functionality breaks
- adding a child doesn't work

is there some working demo of the hybrid chart with all the functions mentioned above working?

**Comment by dabeng** [comment]
Hi @CatalinRadoi From the version 3.4.0, you can drag&drop in the hybrid(horizontal + vertical) chart with the help of [JSONDigger](https://github.com/dabeng/json-digger) utility class. I have created the [Demo](https://codepen.io/dabeng/pen/yLqQGRb) on codepen.io for you.
