### ISSUE TITLE
Export image problems when using l2r and zoom

### ISSUE THREAD

**Issue by danielekbom** [dabeng/OrgChart#53]
I am getting problems when using Export Image with a chart in l2r direction.
I also get similar problems when exporting image after I have zoomed the chart (which also happens in t2b direction mode).

The edges (lines) between the nodes gets messed up.

I have modified the chart script quite a lot so I am not sure that the problems is because of this. Maybe someone else can try to see if they also get these problems.

**Comment by dabeng** [comment]
Hi @danielekbom , can you upload some snapshots to show the bugs you came into?

**Comment by dabeng** [comment]
Additionally, I guess the most of the problems you mentioned above are probably caused by html2canvas.js. Because currently it's not fully compatible with CSS3 tranform which have been used widely in the orgcharts that enable direction option.
