### ISSUE TITLE
Drag and Drop for vertical nodes not working

### ISSUE THREAD

**Issue by Surjitsinght** [dabeng/OrgChart#530]
Hi,

I am trying to achieve drag and drop functionality for vertical nodes.is it possible?

The github links displays below statement:
Note: currently, this option is incompatible with many other options or methods, like direction, drag&drop, addChildren(), removeNodes(), getHierarchy() and so on. These conflicts will be solved one by one in the later versions.

Any update on this?

Please Help

**Comment by dabeng** [comment]
Hi @Surjitsinght From the version 3.4.0, you can drag&drop in the hybrid(horizontal + vertical) chart with the help of [JSONDigger](https://github.com/dabeng/json-digger) utility class. I have created the [Demo](https://codepen.io/dabeng/pen/yLqQGRb) on codepen.io for you.
