### ISSUE TITLE
Problem with drag/drop node in l2r direction

### ISSUE THREAD

**Issue by danielekbom** [dabeng/OrgChart#54]
I am getting problems then using Drag & Drop node in l2r direction mode.
The problem is that when dragging a node, then the "cloned ghost node" that follows the mouse when dragging is rotated 90 degrees.

**Comment by dabeng** [comment]
Thank you for your deep use of OrgChart plugin. I'll check the collision between these two options ASAP.

**Comment by dabeng** [comment]
Hi @danielekbom , the collision between option direction and option draggable has been fixed in version 1.2.2
