### ISSUE TITLE
Enhancement: Make the zoom and panning work with touch screens

### ISSUE THREAD

**Issue by danielekbom** [dabeng/OrgChart#55]
My chart looks perfect on mobile phones right now, which is great!
Except from one thing: The zooming and panning of the chart does not work, which is important because right now the user is only able to see a small part of the chart on mobile phones.

I am planning to implement buttons for navigation that mobile phone users can use. But if the panning and zooming functionality worked it would be much better :)

**Comment by dabeng** [comment]
Wow! It's a awesome feature. I'll think about it seriously. I'm sure it will appear on the version 2.0.

**Comment by dabeng** [comment]
Hi @danielekbom , I'm glad to tell you OrgChart plugin is touch-enabled on mobile device since version 1.2.3. Please try it out and give us feedback.
