### ISSUE TITLE
when I add a node I want to get three fields (id, title, name) 

### ISSUE THREAD

**Issue by sasa1000** [dabeng/OrgChart#56]
hello!  my problem is that when I add a node I want to get three fields (id, title, name) in this example http://dabeng.github.io/OrgChart/edit-orgchart/
you can put just a value for the node and you cannot export it after in  json because it doesn't have an id. can you help me please?

**Comment by dabeng** [comment]
Hi @sasa1000 ,I have just updated example [edit-orgchart](http://dabeng.github.io/OrgChart/edit-orgchart/)(just append the simple and direct automatic id generation mechanism based on javascript timestamp) so that users can export the current hierarchy into the json object
