### ISSUE TITLE
Import & Export Chart data from mySQL

### ISSUE THREAD

**Issue by KRE87** [dabeng/OrgChart#57]
I'm new to javascript and I'm looking to use this excellent OrgChart tool to allow me to edit Org Charts, and to save this new chart data to a mySQL database. It would allow me to then come back to a saved Org Chart where they could continue to make changes. Ideally, in the edit orgchart example, I'd have a Save button.

 I saw that there was something from @JordiCorbilla but I couldn't see how I could implement it myself. Is this something that would be quite straightforward?

**Comment by JordiCorbilla** [comment]
You'll have to do it yourself. I serialize/deserialize the json string and save the details in the DB. Now I have a complete chart that loads from the DB and get saved into it too.

**Comment by KRE87** [comment]
Thanks for the quick response. I've been trying to work it out but I'm new to javascript so I'm trying to understand how, after changing the chart, where the data source is exactly to export it to the database. I'll keep researching and try and figure it out, thanks again.

**Comment by sasa1000** [comment]
after changing the chart did you get the new  hierarchy with json?

**Comment by JordiCorbilla** [comment]
Yes, I'm getting the json via getHierarchy and then I send the everything to my controller via Ajax. There I work out the changes and modify the DB accordingly and refresh the site again with the changes.:

```
var hierarchy = $('#chart-container').orgchart('getHierarchy');

var tree = JSON.stringify(hierarchy, null, 2);
            $.ajax({
                type: "POST",
                url: "http://localhost/Organization/SaveData?tree=" + tree,
                success: function (data) {
                    $('#btn-export-hier').after('<pre>').next().append(data.data);
                },
                dataType: "json",
                traditional: true
            });
```

**Comment by sasa1000** [comment]
can you help me I didn' t found a solution for this error "Error: Nodes of orghcart to be exported must have id attribute!"

**Comment by JordiCorbilla** [comment]
yes, basically when you generate the chart you need to specify the id attribute.

date: "{"id" : "1", "name": "user1", "title": "manager", "children": [{ "id" : "2",....

So you need to work out how to add an id to each node. Basically I have a table with all my users and I use the identity column of the table to give a unique id to each node. I also build the json string from the DB so it's easy to populate all the values.

**Comment by sasa1000** [comment]
thanks for your reponse but here is what is blocking me is how to add an identifier to each node added I am a beginner in js I tried several things but nothing works and I can't export  the new  chart in json  if you have more details I am taking ..

**Comment by JordiCorbilla** [comment]
It would be something like this

````
var datascource = {
  'id': '1',
  'name': 'Lao Lao',
  'title': 'general manager',
  'className': 'top-level',
  'children': [
    { 'id': '2', 'name': 'Bo Miao', 'title': 'department manager', 'className': 'middle-level',
      'children': [
        { 'id': '3', 'name': 'Li Jing', 'title': 'senior engineer', 'className': 'bottom-level' },
        { 'id': '4', 'name': 'Li Xin', 'title': 'senior engineer', 'className': 'bottom-level' }
      ]
    }
  };
````

**Comment by sasa1000** [comment]
yes it work I gave each node has an id and it works and  I had the hierachy in json but my problem is the node added I don't know how to give it an id to will be exported as json too
I don't know if a change is necessary at this level
 $('#btn-add-input').on('click', function() {
      $('#new-nodelist').append('<ul> <input type="text"   class="new-node"></ul>');
    });

    $('#btn-remove-input').on('click', function() {
      var inputs = $('#new-nodelist').children('ul');
	
      if (inputs.length > 3) {
        inputs.last().remove();
      }
    });

    $('#btn-add-nodes').on('click', function() {
      var $chartContainer = $('#chart-container');
      var nodeVals = [];
      $('#new-nodelist').find('.new-node').each(function(index, item) {
        var validVal.title = item.value.trim();
		
        if (validVal.length) {
          nodeVals.push(validVal);
        }
      });
      var $node = $('#selected-node').data('node');
      if (!nodeVals.length) {
        alert('Please input value for new node');
        return;

**Comment by JordiCorbilla** [comment]
See the example under "edit chart" in there you'll see how to return a json string with the parameters you need. In there you'll have to add the id parameter.

**Comment by sasa1000** [comment]
yes I saw it but it just add a text which represent after the value of the node and i haven't to add the id parameter  I apologize if I bothered you  with my questions :/

**Comment by JordiCorbilla** [comment]
you need to use the nodeVals.map() and return the json string in there with the id.

**Comment by sasa1000** [comment]
but i'am not using map i wan't just to set an id to each  new node added after using 'edit chart'

**Comment by sasa1000** [comment]
@JordiCorbilla  

var hierarchy = $('#chart-container').orgchart('getHierarchy');

var tree = JSON.stringify(hierarchy, null, 2);
            $.ajax({
                type: "POST",
                url: "http://localhost/Organization/SaveData?tree=" + tree,
                success: function (data) {
                    $('#btn-export-hier').after('<pre>').next().append(data.data);
                },
                dataType: "json",
                traditional: true
            });  in this function what represents url and data ?

**Comment by Daxong** [comment]
I cannot get new hierarchy after drag by getHierarchy(),or I should ask how to get new hierarchy.
```
var oc = $('#org-chart').orgchart({
        'data' : datascource,
        // 'nodeContent': 'title',
        "nodeId":"id",
        "parentNodeSymbol":'',
        'draggable': true,
        "exportButton":true,
        'dropCriteria': function($draggedNode, $dragZone, $dropZone) {
          if($draggedNode.find('.content').text().indexOf('manager') > -1 && 
            $dropZone.find('.content').text().indexOf('engineer') > -1) {
            console.log(false);
            return false;
          }
          return true;
        }
      });
var str=oc.getHierarchy();
console.log(str);
```

**Comment by doarsal** [comment]
http://creappti.com/scripts/orgChart/

**Comment by jineshsubedi** [comment]
I got this error while exporting json data

`{
  "$chartContainer": {
    "0": {
      "jQuery341063933117036619791": {
        "events": {
          "click": [
            {
              "type": "click",
              "origType": "click",
              "guid": 80,
              "selector": ".node",
              "needsContext": false,
              "namespace": ""
            },
            {
              "type": "click",
              "origType": "click",
              "guid": 81,
              "selector": ".orgchart",
              "needsContext": false,
              "namespace": ""
            }
          ]
        }
      }
    },
    "length": 1
  },
  "opts": "getHierarchy",
  "defaultOptions": {
    "nodeTitle": "name",
    "nodeId": "id",
    "toggleSiblingsResp": false,
    "visibleLevel": 999,
    "chartClass": "",
    "exportButton": false,
    "exportFilename": "OrgChart",
    "exportFileextension": "png",
    "parentNodeSymbol": "fa-users",
    "draggable": false,
    "direction": "t2b",
    "pan": false,
    "zoom": false,
    "zoominLimit": 7,
    "zoomoutLimit": 0.5
  },
  "options": {
    "0": "g",
    "1": "e",
    "2": "t",
    "3": "H",
    "4": "i",
    "5": "e",
    "6": "r",
    "7": "a",
    "8": "r",
    "9": "c",
    "10": "h",
    "11": "y",
    "nodeTitle": "name",
    "nodeId": "id",
    "toggleSiblingsResp": false,
    "visibleLevel": 999,
    "chartClass": "",
    "exportButton": false,
    "exportFilename": "OrgChart",
    "exportFileextension": "png",
    "parentNodeSymbol": "fa-users",
    "draggable": false,
    "direction": "t2b",
    "pan": false,
    "zoom": false,
    "zoominLimit": 7,
    "zoomoutLimit": 0.5
  },
  "$chart": {
    "0": {
      "jQuery341063933117036619792": {
        "options": {
          "0": "g",
          "1": "e",
          "2": "t",
          "3": "H",
          "4": "i",
          "5": "e",
          "6": "r",
          "7": "a",
          "8": "r",
          "9": "c",
          "10": "h",
          "11": "y",
          "nodeTitle": "name",
          "nodeId": "id",
          "toggleSiblingsResp": false,
          "visibleLevel": 999,
          "chartClass": "",
          "exportButton": false,
          "exportFilename": "OrgChart",
          "exportFileextension": "png",
          "parentNodeSymbol": "fa-users",
          "draggable": false,
          "direction": "t2b",
          "pan": false,
          "zoom": false,
          "zoominLimit": 7,
          "zoomoutLimit": 0.5
        }
      },
      "jQuery341063933117036619791": {
        "events": {
          "click": [
            {
              "type": "click",
              "origType": "click",
              "data": null,
              "guid": 122,
              "namespace": ""
            }
          ]
        }
      }
    },
    "length": 1
  }
} edit:773:17
SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"`

**Comment by jineshsubedi** [comment]
SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"

got this error while exporting json data

**Comment by jineshsubedi** [comment]
{
  "$chartContainer": {
    "0": {
      "jQuery341080066302814189971": {
        "events": {
          "click": [
            {
              "type": "click",
              "origType": "click",
              "guid": 80,
              "selector": ".node",
              "needsContext": false,
              "namespace": ""
            },
            {
              "type": "click",
              "origType": "click",
              "guid": 81,
              "selector": ".orgchart",
              "needsContext": false,
              "namespace": ""
            }
          ]
        }
      }
    },
    "length": 1
  },
  "opts": "getHierarchy",
  "defaultOptions": {
    "nodeTitle": "name",
    "nodeId": "id",
    "toggleSiblingsResp": false,
    "visibleLevel": 999,
    "chartClass": "",
    "exportButton": false,
    "exportFilename": "OrgChart",
    "exportFileextension": "png",
    "parentNodeSymbol": "fa-users",
    "draggable": false,
    "direction": "t2b",
    "pan": false,
    "zoom": false,
    "zoominLimit": 7,
    "zoomoutLimit": 0.5
  },
  "options": {
    "0": "g",
    "1": "e",
    "2": "t",
    "3": "H",
    "4": "i",
    "5": "e",
    "6": "r",
    "7": "a",
    "8": "r",
    "9": "c",
    "10": "h",
    "11": "y",
    "nodeTitle": "name",
    "nodeId": "id",
    "toggleSiblingsResp": false,
    "visibleLevel": 999,
    "chartClass": "",
    "exportButton": false,
    "exportFilename": "OrgChart",
    "exportFileextension": "png",
    "parentNodeSymbol": "fa-users",
    "draggable": false,
    "direction": "t2b",
    "pan": false,
    "zoom": false,
    "zoominLimit": 7,
    "zoomoutLimit": 0.5
  },
  "$chart": {
    "0": {
      "jQuery341080066302814189972": {
        "options": {
          "0": "g",
          "1": "e",
          "2": "t",
          "3": "H",
          "4": "i",
          "5": "e",
          "6": "r",
          "7": "a",
          "8": "r",
          "9": "c",
          "10": "h",
          "11": "y",
          "nodeTitle": "name",
          "nodeId": "id",
          "toggleSiblingsResp": false,
          "visibleLevel": 999,
          "chartClass": "",
          "exportButton": false,
          "exportFilename": "OrgChart",
          "exportFileextension": "png",
          "parentNodeSymbol": "fa-users",
          "draggable": false,
          "direction": "t2b",
          "pan": false,
          "zoom": false,
          "zoominLimit": 7,
          "zoomoutLimit": 0.5
        }
      },
      "jQuery341080066302814189971": {
        "events": {
          "click": [
            {
              "type": "click",
              "origType": "click",
              "data": null,
              "guid": 123,
              "namespace": ""
            }
          ]
        }
      }
    },
    "length": 1
  }
}
