### ISSUE TITLE
Problem with drag/drop and pan/zoom

### ISSUE THREAD

**Issue by fhisashi** [dabeng/OrgChart#58]
I'm having troubles with drag/drop when pan/zoom is activated.
If you activate pan/zoom, make some iterations then try to drag some object, them you get the object in wrong position while still dragging.
UPDATE: Only in Firefox

**Comment by dabeng** [comment]
Thank you for your deep use of OrgChart plugin. I'll check the collision between these two options.

**Comment by dabeng** [comment]
Hi @fhisashi , the collision between option draggable and option pan&zoom has been fixed in version 1.2.2
