### ISSUE TITLE
Is it possible to design the node ?

### ISSUE THREAD

**Issue by ji-tusher** [dabeng/OrgChart#595]
I wish If I could design the node by myself. Is there any way to add any images or div instead of showing just a text. Suppose If I use it for a team chart. Here I will put an image, name, designation, contact information.

**Comment by kishan-getstarted** [comment]
you can use `nodeTemplate` params to customised node. here is a small example. 

```
this.orgChart = ($('#chart-container') as any).orgchart({
        data: orgData,
        pan: true,
        zoom: true,
        nodeTemplate: this.nodeTemplate,
        initCompleted: () => { },
      });

// Separate Function
nodeTemplate = (data) => {
      return `
      <div class="text">${data?.question}</div>
      <img src="${data.imgUrl}/>
    `;
  };
```
