### ISSUE TITLE
 i wan't to set an id to each new node added after using 'edit chart'

### ISSUE THREAD

**Issue by sasa1000** [dabeng/OrgChart#60]
hello , 
 I didn' t found a solution for this error "Error: Nodes of orghcart to be exported must have id attribute!" my problem that the node added can't be exported in json .
can you help me ?

**Comment by dabeng** [comment]
Hi sasa1000, you just need to modify the edit-chart example a little to fulfill your demand. On the one hand, you should initialize the chart with datasource including id property. On the other hand, you should provide another input box to allow users to input unique id for every new node or provide an automatic generation mechanism of id. At last, you could easily export the hierarchy of orgchart in which every node has id attribute.

**Comment by sasa1000** [comment]
thanks for your help ! I tried to  provide an automatic generation mechanism of id but it dosen t work you can help me ? 
this is my fonction
(function(){
    var counter = 13; ( the last id in the datascource)
    window.uniqueId = function(){
        return   counter++
    }
});


$('.new-node').each(function (i, e) {
  var name = uniqueId();
  $(e).find(':input').each(function (j, f) {
    var id = uniqueId();
    $(f).attr('name', name)
        .attr('id', id)
      .next()
        .attr('title', title);
  })
});
and i tried to  provide another input box to allow users to input unique id , and name and title but in this moment the button add dosen't work 
this is my html
<label>new node:</label>
    <ul id="new-nodelist" class="new-node">
      <li> <input type="text" "text" name="name" ></li>
	  <li> <input type="text" "text" name="id" >
	  <li> <input type="text" "text" name="title">
    </ul>

There are several problem in my current code you ca help me ?

**Comment by sasa1000** [comment]
i tried to provide an automatic generation mechanism of id but it dosen't work this is my code
https://jsfiddle.net/g5hLo0bo/8/

**Comment by dabeng** [comment]
Hi @sasa1000 ， I have updated the [edit-chart demo](http://dabeng.github.io/OrgChart/edit-orgchart/) according to your demand, please try it out.
