### ISSUE TITLE
如果初始化的时候选择了纵向排列'verticalLevel': 4,  新添加的元素还是横向的

### ISSUE THREAD

**Issue by flowerxuegao** [dabeng/OrgChart#608]
初始化的代码，添加了'verticalLevel': 4,，纵向排列
var oc = $('#chart-container').orgchart({
      'data' : datascource,
      'chartClass': 'edit-state',
      'exportButton': false,
      'exportFilename': 'SportsChart',
	  "pan":false,
	  "zoom":true,
	  'verticalLevel': 4,
	  'nodeContent': 'title',
	  "draggable":true,
	  "toggleSiblingsResp":false,
      'createNode': function($node, data) {
        $node[0].id = getId();
      }
    });
edit-chart这个demo里面新增的元素还是横向排列

**Comment by dabeng** [comment]
Hi @flowerxuegao ，你可以基于这个例子（https://dabeng.github.io/OrgChart/edit-hybrid-chart.html）改造一下，看看还有什么问题
