### ISSUE TITLE
Export button positioning change in 3.1.1

### ISSUE THREAD

**Issue by PrzemyslawKlys** [dabeng/OrgChart#610]
Would it possible to make it customizable for the export button positioning?

Version: 3.1.0

![image](https://user-images.githubusercontent.com/15063294/108605913-4b08a800-73b7-11eb-8915-785d7f3eff03.png)

Version: 3.1.1

![image](https://user-images.githubusercontent.com/15063294/108605921-552aa680-73b7-11eb-98d7-8be7dfbd5ed3.png)

I understand not everyone prefers one or the other so maybe some kind of choice where it should be located?

**Comment by dabeng** [comment]
Hi @PrzemyslawKlys . Since version 3.1.1, I moved export button out of chart-container div to allow users to place that button more easily.

**Comment by dabeng** [comment]
For example, you can include this export button into your button group about orgchart.

**Comment by PrzemyslawKlys** [comment]
I do understand your goal - just right now it's taking all the whitespace I have. I guess I'll have to live with it :-)
