### ISSUE TITLE
Orgchart - static indicator that node can be collapsed/expanded without mouseenter/ mouseleave?

### ISSUE THREAD

**Issue by jxmai** [dabeng/OrgChart#621]
Currently the arrow indicators only show up on mouse hover, it is not immediately obvious that which node can be expanded / collapsed without hovering on every single node.

For example, It is not immediately obvious that there is a child node to `Node4` unless we hover on that.
![image](https://user-images.githubusercontent.com/10467831/123844371-91779180-d8d8-11eb-9a5c-2cb518e79ceb.png)

(We cannot tell which node has child by the static view)

![image](https://user-images.githubusercontent.com/10467831/123844766-06e36200-d8d9-11eb-9db0-5fe181de3560.png)

@dabeng We would like to confirm if 
1. If there's any built-in way to do it? 
2. If there's no built-in way, would you be able to accept such option if we come up with a fix for it?

**Comment by asidpulse** [comment]
@jxmai 
Any node that has an icon in the top left has children.
I have outlined the icons in the image below.
![orgChart-titleIcon](https://user-images.githubusercontent.com/5437743/212985299-82038a61-ba02-4a13-b534-01126a5457fb.png)

**Comment by jxmai** [comment]
Hello @asidpulse :wave:  Great observation and thank you for sharing! It is showing in the my original image but I did not pay attention to that. In that case, yes, it should be working fine and I would close this ticket.
