### ISSUE TITLE
Allow functions in AjaxURLS

### ISSUE THREAD

**Issue by jeff-crosstalent** [dabeng/OrgChart#63]
Hi,

It would be helpful to have functions instead of URLs for the AJAX fetching as it would allow a more flexible treatment of the results.
For example we could have something like this:

```
$('#chart-container').orgchart({
  'data' : datascource,
  'ajaxURL': {
      'children': function (nodeId, callback) { //Where nodeId is the node being clicked on
          //Retrieve and do something with the data
      },
      'parent': url
  },
  'nodeContent': 'title',
  'nodeId': 'id'
});
```

Cheers,

**Comment by dabeng** [comment]
Hi @jeff-crosstalent , sorry so late to reply to you. It's awesome idea. I'll introduce this feature into the next version :blush:

**Comment by dabeng** [comment]
Hi @jeff-crosstalent , starting with version 1.2.4, you can use function to build out option ajaxURL.

**Comment by jeff-crosstalent** [comment]
Great!
Thanks for your help.
