### ISSUE TITLE
节点绑定jq事件不起效

### ISSUE THREAD

**Issue by godletfhand0** [dabeng/OrgChart#639]
$('.node').on('click', function(){ 

        alert("Hello World"); 
      });

**Comment by mm05112** [comment]
你的邮件我已收到，愿七色之夏的光辉永远守护你

**Comment by dabeng** [comment]
@godletfhand0  节点的单击事件是有效的，可以绑定的。可以参考codepen上的汇报路径demo -- https://codepen.io/dabeng/pen/eYBRPYN
