### ISSUE TITLE
Max depth of 31 on Firefox

### ISSUE THREAD

**Issue by GabrielCW** [dabeng/OrgChart#64]
Hey there,

I've tried several plugins in order to do an org chart (including [wesnolte's](https://github.com/wesnolte/jOrgChart) and [mozg's](https://github.com/mozg1984/jOrgChart)), and I always have the same issue, that I also have with OrgChart. On Chrome, everything is fine, the tree is always rendered in its entirety.

On Firefox though (and customers have reported, on Safari as well), the tree just stops rendering at the 31st node in depth.

Am I the only one to have this problem? Anyone know how to circumvent it?
Or is it just that some browsers have a hard limit on DOM nodes depth?

**Comment by azureskydiver** [comment]
Off topic:
Not to invalidate the bug that you are reporting, but perhaps there is something wrong with your organization if there are more than 30 layers deep from the head of the organization down to the lowest pawn. Most modern organizations try not to have more than 16 levels between top management and the lower rung worker.

Back on topic:
I found the issue with FireFox when I was trying to fix the issue of demand loading nodes an my source data had an infinite loop at the top of the org. As you noted Chrome worked just fine.

**Comment by dabeng** [comment]
Sorry about that. To now, I haven't do a full test to checkout out what's the maximal render depth of orgchart plugin. I'll complement this kind of work.

**Comment by dabeng** [comment]
Hi @GabrielCW , you guess right. In Firefox, deeply nested elements are not rendered. It's an inherent bug of Firefox. So the max depth of 31 is irrelevant to plguin orgchart itself. For more details, you could refer to https://bugzilla.mozilla.org/show_bug.cgi?id=256180.

**Comment by GabrielCW** [comment]
Thank you for this confirmation. For the record, I ended up using treant.js to solve my problem.
