### ISSUE TITLE
Can not change parent of node when setting verticalLevel

### ISSUE THREAD

**Issue by luantm16110560** [dabeng/OrgChart#650]
Hello team dev, I am using OrgChart and I have an issue

I create new org chart and it's has attribute verticalLevel , then I enable draggable: true , I can drag and drop normally but parent_id of node does not correctly. please support to me

Here is my custom code:

![image](https://user-images.githubusercontent.com/43678069/175000117-5485275d-1a15-40be-9d51-94337edc5063.png)

![e94037442042e31cba53](https://user-images.githubusercontent.com/43678069/174998817-cff89204-f2e3-4045-ad81-faf91c1941eb.jpg)

Result is

![deb991678a61493f1070](https://user-images.githubusercontent.com/43678069/174998873-6cf717da-b512-464a-a946-21a158179245.jpg)

Expect like this

![image](https://user-images.githubusercontent.com/43678069/175000612-b98a1b9a-9848-4cde-91d6-7994fd3d1158.png)

**Comment by dabeng** [comment]
Hi @luantm16110560 From the version 3.4.0, you can drag&drop in the hybrid(horizontal + vertical) chart with the help of [JSONDigger](https://github.com/dabeng/json-digger) utility class. I have created the [Demo](https://codepen.io/dabeng/pen/yLqQGRb) on codepen.io for you.
