### ISSUE TITLE
Cannot addParent() when using jQuery 3.1.0

### ISSUE THREAD

**Issue by azureskydiver** [dabeng/OrgChart#66]
Using jQuery 3.1.0 and loading nodes on demand, I'm unable to explore up the tree as nodes are loaded dynamically. Looks like an exception is thrown while trying to show a node.

Workaround is to use jQuery 2.2.4.

**Comment by dabeng** [comment]
Hi @azureskydiver , this bug has been fixed in version 1.1.5
