### ISSUE TITLE
[Request] Center on node and expand to depth

### ISSUE THREAD

**Issue by St1fle** [dabeng/OrgChart#67]
Hey there!

For my company's project it would be nice if it was possible to center (focus?) on a node and then expand to a given depth.

This could be 2 different functions added to the library. Something like:
$('.orgchart').centerOn(varNode);
and
$('.orgchart').expandFromToDepth(varNode, depth);

What I mean with centerOn is if you click on a team member the diagram focuses on the member but he isn't centered on the div which means the person has to drag about. If you have a huge diagram, you zoom out a lot, click to center on a user, the user disappears from sight and you can't drag to him because the diagram space is too small and out of view. This can even be an option instead of a function called manually, that centers every time a member is selected.

The expandFromToDepth function is basically allowing us to expand to a certain depth when the member is clicked. This is so when we select a member instead of showing just the member alone we expand immediately to a given depth. This is also useful for huge diagrams if we want to see depths of 3 by 3 for example.

I don't know if this is possible and I can't do it myself that's why I'm requesting.

Thank you very much!

**Comment by dabeng** [comment]
Hi @St1fle , thank you for your deep thinking about orgchart plugin. Your demand is very representative and I'll take time to accomplish them.

**Comment by dabeng** [comment]
Hi @St1fle , have a look at [center on selected node](http://codepen.io/dabeng/pen/JRGNjk), it's a prototype based on which you can customize the more details. Good luck!

**Comment by dabeng** [comment]
Hi @St1fle , checkout out [expand to the given depth](http://codepen.io/dabeng/pen/bwEWpp) hoping it can help you.

**Comment by St1fle** [comment]
Hi @dabeng! Thank you so much for taking the time to do this! Yes this is exactly what I was looking for, I can insert this in to the company's graph. Thank you so much really!

**Comment by dabeng** [comment]
Wow! It's my pleasure to see that orgchart plugin is applied in your practical project. :blush:
