### ISSUE TITLE
Edit org chart has no option to edit selected node ?

### ISSUE THREAD

**Issue by XioSC** [dabeng/OrgChart#69]
I want to select a node and change it's name/title, but I can't seem to find a way to do it like when adding/deleting nodes.

**Comment by dabeng** [comment]
you know that the original idea of example is modifying the structure of orgchart rather than modifying node content. It's already a qualified prototype. So users are encouraged to add anything fantastic to this example and build up their own edit-chart. Just have fan:blush:

**Comment by Zmove** [comment]
It would be great to update the edit example with the possibility to edit a selected node.
