### ISSUE TITLE
Custom Icons Support after Font Awesome Icons Removal

### ISSUE THREAD

**Issue by jxmai** [dabeng/OrgChart#695]
Issue: https://github.com/primefaces-extensions/primefaces-extensions/issues/1050

Our current workaround is to replace fa-folder-open to `oci-leader`. (https://github.com/primefaces-extensions/primefaces-extensions/issues/1050#issuecomment-1416599132) However, other than `oci-leader`, there seems no other customized icon exists for parentNodeSymbol.

It would be nice if we  have the list of possible customized icons to be used after the font awesome icons removal or the ability to to define our own icons.

**Comment by melloware** [comment]
Yes I understand removing FontAwesome as a dependency but there should be the ability to plug it back in and use custom icons.

**Comment by dabeng** [comment]
Hi @jxmai @melloware since version 3.7.0, users are allowed to replace built-in icons with Font Awesome icons. I have created demo on codepen.io for you.
https://codepen.io/dabeng/pen/jOezQzy

**Comment by melloware** [comment]
@dabeng thank you!

**Comment by jxmai** [comment]
Thanks @dabeng!
