### ISSUE TITLE
chart aligning starting from left

### ISSUE THREAD

**Issue by veenone** [dabeng/OrgChart#700]
Hi,

I'm trying to integrate your code, however I got this behavior :

![image](https://user-images.githubusercontent.com/3839381/232286589-25b1329e-24ef-4c54-905c-5845f1e62257.png)

where the top is aligning on left side.
How to make all node positioned in center like your examples?

Thank you

**Comment by mm05112** [comment]
你的邮件我已收到，愿七色之夏的光辉永远守护你

**Comment by dabeng** [comment]
Hi @veenone You need to set the text-align property of chart-container div to **"center"**
<img width="1161" alt="Screenshot 2023-04-18 at 09 07 55" src="https://user-images.githubusercontent.com/5689075/232643398-a5457af0-34ed-4384-b343-efb770de4860.png">

**Comment by veenone** [comment]
hi @dabeng,
great! thanks for answering my stupid question :)
I will mark as closed in this case.
