### ISSUE TITLE
alternate layout if children is too many

### ISSUE THREAD

**Issue by veenone** [dabeng/OrgChart#701]
Hi @dabeng,

I have another query, this time is about layout for children which is too many as shown below : 
![image](https://user-images.githubusercontent.com/3839381/232770446-e44a1036-9ae5-4b06-a30c-a5a3e0b06310.png)

the children is spanning across the screen since I have around 30+ people under a manager.
Is there a way to make it simpler? so all children can fit in a screen?
I'm thinking to have a layout like the following : 

![image](https://user-images.githubusercontent.com/3839381/232771319-27c4a6b7-e5f8-4074-bfa9-e64b41464a58.png)

or some other layout which is more compact, like vertical layout with 2 or 3 column but from the same parent.

Thank you

**Comment by dabeng** [comment]
Hi @veenone You can make use of options -- isHybrid or verticalLevel to build up hybrid(horizontal + vertical) chart. The following are related demos on codepen.io

- https://codepen.io/dabeng/pen/eYPBvRa
- https://codepen.io/dabeng/pen/LYbLMqb

**Comment by dabeng** [comment]
@veenone  I have released v 3.8.0. You can use data option "compact" or option "compact" to build up compact node as shown below.
<img width="1154" alt="687474703a2f2f646162656e672e6769746875622e696f2f4f726743686172742f696d672f646174612d70726f702d636f6d706163742e706e67" src="https://github.com/dabeng/OrgChart/assets/5689075/0e5e4295-bdcf-48df-b019-5d689b2a4ae2">
You can also play around this demo -- https://codepen.io/dabeng/pen/GRwjRJy
