### ISSUE TITLE
[feature request] Structure for genealogy/pedigree/family tree

### ISSUE THREAD

**Issue by drabanus** [dabeng/OrgChart#708]
This is more a feature request than an issue: I would like to use this framework for visualizing genealogy/pedigree/family tree information, i.e there are 2 parents for a number of children. Currently I don't see how that can be entered into the data input file. 

If this is already possible, any hints on how to do that?

If not, could this be integrated as feature into a future version? 

Regards and thanks in advance - David

**Comment by strtob** [comment]
Hi, 

this is a really amazing libary! I have the some problem. I would like to visualizing company stucture, so two more companies (1 tier), will own one company (2 tier), and this company could own 2 companies alone (3 tier).

Is there any possibility to show this structure?

Best,
Toby

**Comment by n1colius** [comment]
Also plus 1 for this feature, been searching for library that can handle this kind of data

**Comment by mm05112** [comment]
你的邮件我已收到，愿七色之夏的光辉永远守护你

**Comment by dabeng** [comment]
Hi @strtob @n1colius Since version 5.0.0, users are allowed to build up family tree. FYI, please play around the demo -- https://dabeng.github.io/OrgChart/family-tree.html

**Comment by strtob** [comment]
Great! Are allowed that are more then 2 parents to use at the same time? That's essentially for holding charts. 

Is it also possible to add figers like percentage shares?

Thanks a lot!
