### ISSUE TITLE
Is it possible to include vertical org chart a JS parameter?

### ISSUE THREAD

**Issue by gurumark** [dabeng/OrgChart#71]
Instead of trying to figure out CSS transform values. Is it possible to include vertical org chart a JS parameter?

**Comment by dabeng** [comment]
Sorry @gurumark , I'm not sure I got your point. Could the option "verticalDepth" fulfill your demand? Please refer to this [demo](http://dabeng.github.io/OrgChart/vertical-depth/).

**Comment by gurumark** [comment]
I think it is definitely right direction to go. I liked the arrows better. Instead of showing the +/-, it would be better to stick to arrows ie. when user clicks on down arrow, it will show the depth.

**Comment by dabeng** [comment]
No problem, if you prefer fa-chevron-down than fa-plus-square. It's up to you to customize a particular version of orgchart plugin. However, I sill believe plus/minus icon is better than direction arrows. Using plus/minus icons means that users can expand/collapse child nodes like directory tree.
