### ISSUE TITLE
Regression: Drag and Drop is not functional in the demo page

### ISSUE THREAD

**Issue by jxmai** [dabeng/OrgChart#712]
**Regression description**: The drag and drop feature is not functional in the latest version

**Ways to replicate:** Go to https://dabeng.github.io/OrgChart/drag-drop.html, and try to drag and drop any node.

**Expected behavior:** Drag and drop feature should be working

**Actual behavior:** Drag and drop isn't working

**Impact:** This is crucial regression as drag and drop feature is widely used.

**Comment by jxmai** [comment]
@dabeng Could you please verify the regression whenever you have a chance? If drag and drop feature is broken in orgchart, it should have board impact of the usability of this component. Thanks!

**Comment by jxmai** [comment]
Link to: https://github.com/primefaces-extensions/primefaces-extensions/issues/1182

**Comment by jxmai** [comment]
The github demo missed https://www.npmjs.com/package/json-digger dependency. It looks like demo issue only.

In the demo, https://dabeng.github.io/OrgChart/drag-drop.html

There's no`json-digger.js`

![image](https://github.com/dabeng/OrgChart/assets/10467831/4b8b2966-a359-4ba5-885f-f74e22b38dc6)


![image](https://github.com/dabeng/OrgChart/assets/10467831/d65f8f4f-54c8-4963-a743-26783369a8bd)



However, when running the demo on local, http://localhost:3000/drag-drop.html, `json-digger.js`.

![image](https://github.com/dabeng/OrgChart/assets/10467831/3108c593-1da2-471e-a005-a464b5717639)

![image](https://github.com/dabeng/OrgChart/assets/10467831/da8bf791-3de1-4a7e-8c07-6e76350a8f81)

**Comment by jxmai** [comment]
@dabeng After https://github.com/dabeng/OrgChart/commit/28f797a9f2ae77896ce387d9c6de144e2cea4226#diff-24a5fef88d585add1c01eb9b69b37c6875761e6088fdfc7ace2035c2e3377e9dR1123-R1134, the orgchart lib can only run on nodeJS specific environment because of the dependency of: js/json-digger.js. Previously jquery orgchart is highly portable to any environemnt.

**Comment by dabeng** [comment]
The drag and drop feature is functional in the latest version

**Comment by jxmai** [comment]
Hello @dabeng :wave:  I would like to clarify a point regarding the recent changes in version 3.4.0. Since the introduction of this file: https://raw.githubusercontent.com/dabeng/json-digger/refs/heads/master/dist/json-digger.js via https://github.com/dabeng/OrgChart/commit/28f797a9f2ae77896ce387d9c6de144e2cea4226#diff-24a5fef88d585add1c01eb9b69b37c6875761e6088fdfc7ace2035c2e3377e9dR1123-R1134, it appears that webpack is now required to run OrgChart.

Previously, we were able to use standalone JS and CSS files, which offered greater portability. Unfortunately, without using webpack, we’re unable to upgrade to the latest version.

**Could you please confirm if this is intended or if there's an alternative approach for those not using webpack?**

Thank you in advance!
