### ISSUE TITLE
如何通过参数设置隐藏兄弟节点

### ISSUE THREAD

**Issue by icq224639289** [dabeng/OrgChart#725]
我只知道可以使用collapsed参数隐藏子节点，但是通过什么方式可以隐藏兄弟节点

**Comment by dabeng** [comment]
注意下图，如果你想隐藏“Li Jing”节点的同级节点，你需要使用红框标识的类：
<img width="1233" alt="Screenshot 2023-11-25 at 07 51 17" src="https://github.com/dabeng/OrgChart/assets/5689075/072a1d3c-ad54-4aab-89e1-e7fb4ddc5cde">
