### ISSUE TITLE
ajaxURL

### ISSUE THREAD

**Issue by jieniyou** [dabeng/OrgChart#730]
怎么处理后端数据字段不一致，可以有回调自定义处理数据格式吗

**Comment by dabeng** [comment]
@jieniyou 你好，我新发布了4.0版本，这个版本里，ajaxURL被去除，用户可以完全掌控数据源的获取和格式预处理 -- https://dabeng.github.io/OrgChart/ondemand-loading-data.html

**Comment by jieniyou** [comment]
解你忧 自动回复:你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
