### ISSUE TITLE
Convert Excel file to JSON with Children and Parent

### ISSUE THREAD

**Issue by ehsanmohammadi72** [dabeng/OrgChart#74]
my Excel file include data like this 
![image](https://cloud.githubusercontent.com/assets/20454582/18630006/da121a8c-7e7e-11e6-80a8-e4cc9d7203a9.png)
0 is the parent and have 1,2,3 as child
1 have 1.1 and 1.2 as child
1.1 have 1.1.1 as child 
and ...
about 2000 line in excel 
i want to convert my excel file to JSON code Automatically that include child and parent to use in orgchart . 
![image](https://cloud.githubusercontent.com/assets/20454582/18630183/fd05f3e6-7e7f-11e6-8a99-cf175e395e5c.png)
the final code is something like this .
`'id': '0', 'name': 'name 0', 'title': 'title 0',
      'children': [
        { 'id': '1','name': 'name 1', 'title': 'title 1',
		'children': [   
              { 'id': '1.1','name': 'name 1.1', 'title': 'title 1.1',
                'children': [
                  { 'id': '1.1.1','name': 'name 1.1.1', 'title': 'title 1.1.1' }
                ]
              },
			  { 'id': '1.2','name': 'name 1.2', 'title': 'title 1.2' }
            ]
		},
        { 'id': '2','name': 'name 2', 'title': 'title 2' },
		 { 'id': '3','name': 'name 3', 'title': 'title 3' }
      ]
    };`
i find this [https://shancarter.github.io/mr-data-converter/](url) that convert excel to JSON , but my problem is in Hierarchy , and how add children in this convertor .

**Comment by dabeng** [comment]
Hi @ehsanmohammadi72 , I have reviewed Mr. Data Converter. From my point of view, it can not help you to construct qualified datasource of orgchart. You need to find another third-party tool or to create a  converter by yourself. The point is that you have to loop every row in your excel file and create a JSON object according to the id value which implies the nested relationship.

**Comment by ehsanmohammadi72** [comment]
tnx for response , i found this [http://stephenjamescode.blogspot.com/2013/03/building-tree-in-javascript-to-convert.html](url)
but i dont know where the hierarchical json that this generates is save ?!

**Comment by dabeng** [comment]
Hi @ehsanmohammadi72 , I have reviewed the DataStructures.Tree you mentioned above. I find that the variable "tree" in the js code snippets of index page is what you want, but you still need to refactor the "DataStructures" class so that its returned result can be used as datasource for orgchart plguin.
![screenshot from 2016-10-11 15-26-35](https://cloud.githubusercontent.com/assets/5689075/19262112/d06ccd6e-8f5a-11e6-9763-8ed6cde6e2fd.png)

**Comment by ehsanmohammadi72** [comment]
Tnx for response @dabeng , can i use `JSON.stringify(tree)` to log the JSON ?

**Comment by dabeng** [comment]
Yes, you can , but the key point is that the format of  variable "tree" doesn't match the datasource required by orgchart plugin. You have to adjust the internal structure of variable "tree".
