### ISSUE TITLE
Drag & Drop : Parent node shouldn't be able to be dragged & dropped to a child node on Internet Explorer (IE)

### ISSUE THREAD

**Issue by cwal92** [dabeng/OrgChart#76]
Hi @dabeng, IE allows me to drag & drop a parent node to a child node, then the node disappears. For example, I dragged "Hei Hei" to "Pang Pang", then it disappears. From what I understand, this shouldn't happen. I've attached the screenshots below as a reference to the issue. Please assist. Thanks in advance.

Before dragging a parent node :
![drag_drop_ie_1](https://cloud.githubusercontent.com/assets/22341445/18703963/a68f80b2-801a-11e6-9c85-3fa6ee6fb8b1.png)

After dragging a parent node :
![drag_drop_ie_2](https://cloud.githubusercontent.com/assets/22341445/18703962/a665a2e2-801a-11e6-9c82-b7d88d804c74.png)

**Comment by dabeng** [comment]
Hi @cwal92 , sorry late to reply to you. It's my carelessness. I'll take the time to fix it ASAP :blush:

**Comment by cwal92** [comment]
Hi @dabeng, thank you for your reply.

**Comment by dabeng** [comment]
Sorry cwal92, I'm not going to fix this bug due to the poor support of IE for HTML5 drag & drop API.

**Comment by slgoodson** [comment]
@cwal92 Were you able to find a work-around? Also dealing with this IE related bug as well as IE ignoring dropCriteria. :-/
