### ISSUE TITLE
New Requirement

### ISSUE THREAD

**Issue by Mmannem** [dabeng/OrgChart#78]
How can we find a node inside the chart and show minimized chart of the searched node..

**Comment by dabeng** [comment]
awesome feature, l got it.

**Comment by dabeng** [comment]
Hi @Mmannem , I have created a demo - [filter node](http://dabeng.github.io/OrgChart/filter-node/) according to your demand, please try it out.

**Comment by Mmannem** [comment]
nice...

Thanks

**Comment by ehsanmohammadi72** [comment]
hi @dabeng , in this demo when only root node is visible and search a child node inside the chart ,the root node will be shown only. is very good to expand the chart and show that node .
