### ISSUE TITLE
Error Uncaught TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by fvlima** [dabeng/OrgChart#8]
When the data is requested by a ajax request and when the down arrow of a child node is pressed and there is no parent for it, the orgchart generates error when its trying to retrieve a node that doens't exist and keep a loading image on the screen.

**Comment by dabeng** [comment]
Hi, fvlima, you tried the example -- [ondemand-loading-data](http://dabeng.github.io/OrgChart/ondemand-loading-data/) and got this bug ?

**Comment by fvlima** [comment]
I'm using the ajax datasource example. And I guess that is the point becouse theren't no more parents for a determined node, and the arrow is showed to perform a click to load more data. See my code:

`
$('#id).orgchart({
	'data': '../url/' + id,
	'nodeRelationship': 'level',
	'nodeTitle': 'relationship',
	'nodeChildren': 'parents',
	'nodeContent': 'identification',
	'parentNodeSymbol': '',
	'nodeID': 'id',
	'depth': 4,
	'createNode': function ($node, data) {
		if (data['img'] != undefined) {
			var miniature = $('<i>', {
				'class': 'fa fa-info-circle second-menu-icon',
				click: function () {
					$(this).siblings('.second-menu').toggle();
				}
			});
			var img = '<div class="second-menu">' +
				'<img class="avatar" src="/media/' + data['img'] + '"></div>';
			$node.append(miniature).append(img);
		}
	}
});
`

I know that the error refers to opts.ajaxURL, becouse it doesn't defined, but I chose to not load data on demand, only a initial ajax request.

**Comment by dabeng** [comment]
Hi, fvlima. Does your returned json datasource contain corrent property "level", it's value should be "110" or "111". The three numbers indicate that whether the node has parent node, sibling node or child node.

**Comment by dabeng** [comment]
You know, wrong indicator numbers will result in wrong arrows, and wrong arrows will mislead users to load non-existing nodes.

**Comment by fvlima** [comment]
Hi. I need to ask apologies for my mistake. I thought that if a node had no children, then the orgchart would ignore automatically these empty children nodes. Maybe it can be developed to prevent situations like mine, because were not defined urls to load data on demand.

**Comment by dabeng** [comment]
Hi, fvlima, I got your point, I admit that in most cases, the indicator number is unnecessary except ondemand loading scenario, because in this scenario, orgchart needs some signal to load unknown nodes and in other scenarios, orgchart loads all nodes all at once, orgchart should be capable of generate the right collapsing/expanding arrows according the fixed hierarchy. I'll refine the code as soon as possible.

**Comment by dabeng** [comment]
The idea -- I thought that if a node had no children, then the orgchart would ignore automatically these empty children nodes, has come true in version 0.9.9.7 of orgchart.

**Comment by sirshikher** [comment]
> Hi, fvlima, you tried the example -- [ondemand-loading-data](http://dabeng.github.io/OrgChart/ondemand-loading-data/) and got this bug ?

yes
