### ISSUE TITLE
toggleSiblingsResp not working

### ISSUE THREAD

**Issue by mheptinstall** [dabeng/OrgChart#81]
Toggling the option toggleSiblingsResp does not appear to change anything

**Comment by dabeng** [comment]
Hi @mheptinstall, are you playing around this [demo](http://dabeng.github.io/OrgChart/toggle-sibs-resp/)? It's good without any exception.

**Comment by mheptinstall** [comment]
@dabeng setting the option to false does not appear to change anything. Perhaps I misunderstand what this option actually does as chart behaves the same whether it is set to true or false?

**Comment by dabeng** [comment]
Hi @mheptinstall , enable "toggleSiblingsResp" option, users can expand/collapse the right sibling nodes when they click the right arrow of the current node, while disable this option, users can expand/collapse the all sibling nodes when they click the left/right arrows of the current node.

**Comment by dabeng** [comment]
click right arrow of any node
![screenshot from 2016-09-27 11-28-32](https://cloud.githubusercontent.com/assets/5689075/18859372/1d9e7ccc-8439-11e6-9dc4-6f7229bfe487.png)

result with enabled "toggleSiblingsResp" option
![screenshot from 2016-09-27 11-28-39](https://cloud.githubusercontent.com/assets/5689075/18859386/3a2b9d2a-8439-11e6-8c5a-012f3734040c.png)

result with disable "toggleSiblingsResp" option
![screenshot from 2016-09-27 11-31-40](https://cloud.githubusercontent.com/assets/5689075/18859440/ae1162e2-8439-11e6-8827-d28a0a9b7981.png)

**Comment by mheptinstall** [comment]
Thanks, that now makes sense.
