### ISSUE TITLE
conflict whit Materialize CSS no show Lines

### ISSUE THREAD

**Issue by mariomeraz** [dabeng/OrgChart#83]
Hi 

I have my theme with Materialize, It works well, not just lines.

ideas to fix it ¿?

[Image Lines]
(http://www.lamusiqueexquise.com.mx/bug.png)

**Comment by dabeng** [comment]
Hi @mariomeraz , can you create a demo on jsfiddle or codepen, then I'll help you to fix the bug.

**Comment by mariomeraz** [comment]
[Demo jsfiddle] (https://jsfiddle.net/wxgt4qse/)

Thanks U

**Comment by mariomeraz** [comment]
Ok is ready

[Demo jsfiddle]

(https://jsfiddle.net/mariomeraz/wxgt4qse/7/)

Thaks So Much

**Comment by mariomeraz** [comment]
@dabeng any ideas ? 👍

**Comment by dabeng** [comment]
Hi @mariomeraz , I update the jquery.orgchart.css file. Try out this [demo](https://jsfiddle.net/dabeng/wxgt4qse/11/).

**Comment by mariomeraz** [comment]
Great !! work very nice, thks so mucho @dabeng
