### ISSUE TITLE
Export issue

### ISSUE THREAD

**Issue by Mmannem** [dabeng/OrgChart#84]
![orgchart 1](https://cloud.githubusercontent.com/assets/22373735/18917670/16ba408e-85b6-11e6-83f3-3a729771ee0e.png)

getting red color bars above & below of the chart.

**Comment by dabeng** [comment]
Hi @Mmannem , html2canvas can not support background-image, that's why I add the following code snippets on export-chart demo page.
```css
.orgchart {
  background: #fff;
}
```

**Comment by Mmannem** [comment]
ok., will check.
Thanks for your quick reply.

**Comment by Mmannem** [comment]
Hi,

Above mentioned issue with background image also solved.
Change the CSS like below:
From :
background-image: linear-gradient(90deg, rgba(200, 0, 0, 0.15) 10%, rgba(0, 0, 0, 0) 10%), linear-gradient(rgba(200, 0, 0, 0.15) 10%, rgba(0, 0, 0, 0) 10%);
To:
background:url(../content/images/org-bg.jpg);
![org-bg](https://cloud.githubusercontent.com/assets/22373735/19112678/dace3d3c-8b23-11e6-84d2-b5aafd143659.jpg)
