### ISSUE TITLE
display problem with huge tree

### ISSUE THREAD

**Issue by manuel-84** [dabeng/OrgChart#85]
When I have a huge tree displayed with full opened depth, if I hide all the children of one of the topmost parents then the chart disappear from screen because it does not update its position to center screen

To avoid this problem I created a button that resets the positioning if it's needed

`$('.orgchart').css('transform','');`

**Comment by dabeng** [comment]
Hi @manuel-84 , you are right and your solution is really nice, I'll encapsulate the above code into a new option -- resetButton.

**Comment by manuel-84** [comment]
Actually I'm using a bit more complex code to adapt recentering for huge and little charts

  $('.btnRecenter').click(function() {
    var chart = $('.yourOrgChart');
    var posX = chart.width() > chart.parent('div').width() ? -(chart.width() / 2) : '0';
    chart.css('transform', 'matrix(1, 0, 0, 1, ' + posX + ', 0)');
  });
