### ISSUE TITLE
Can we view and drag employees if they are new (null parentid)?

### ISSUE THREAD

**Issue by SHRIVES23** [dabeng/OrgChart#87]
Currently we have employees that do not have a parentid yet. When the page is returned the datasource only is returning the ones with parentid's (children to the CEO). Is it possible to have the employees with missing parent id's to be floating on the right or left of the page to assign to a parent?

**Comment by dabeng** [comment]
Hi @SHRIVES23 , you know that it's very important to keep the orgchart rigorous for a company. I think it's too casual to let these nodes float on the right/left side. In my opinion, they shouldn't be display on the chart until they get the parentId.
