### ISSUE TITLE
Ability to highlight the path from Child node ->parent node->root node

### ISSUE THREAD

**Issue by pg2203** [dabeng/OrgChart#88]
OrgChart is great library, we have requirement to highlight the child node and its path from root node. I was able to highlight the nodes from root node to child node but i could not highlight(change color of lines) or bold the path lines. is there anyway we can do this.? thanks in advance.

**Comment by dabeng** [comment]
No problem :blush: I'll add the demo link into the tips section of the readme doc. In fact, you almost got the final solution.

**Comment by pg2203** [comment]
Awesome... thanks Dabeng. will wait for your demo link.

**Comment by dabeng** [comment]
Hi @pg2203 , after two days working on this demand, I find that it requires much efforts to draw a path from superior node to inferior node. So I adopted a [compromise plan](http://dabeng.github.io/OrgChart/report-path/). Hope this demo can give you another perspective.

**Comment by pg2203** [comment]
Appreciate your hard work for taking some time to look into this. And thanks for the alternate solution which will not solve the problem i am looking for but will help. Once again thanks for wonderful library.
