### ISSUE TITLE
when I delete child node Can't Add Child node Again

### ISSUE THREAD

**Issue by CanoCheng** [dabeng/OrgChart#9]
When I select Basketball node that add child node TEST1 .
But if I make  a wrong add  child node (TEST1), 
I want to delete that, then do it.
after all , I want to select Basketball this node and add  any child node Again ，
but NOW I can't add any child node

**Comment by dabeng** [comment]
Hi CanoCheng. Insufficient testing results in this bug, I apologize for this. Now this bug has been fixed in version 0.9.9.9
