### ISSUE TITLE
Zooming where is cursor of mouse

### ISSUE THREAD

**Issue by Laurianti** [dabeng/OrgChart#92]
Why zoom works only zooming on center? And not where is the cursor of mouse? It is possible? Thank you

**Comment by dabeng** [comment]
Hi @Laurianti . It require lots of efforts to allow users to zoom in/out on the orgchart based on the cursor position. I'm not optimistic about this input-output ratio.

**Comment by Laurianti** [comment]
I don't understand the real difficulty.
https://jsfiddle.net/uhoekk0v/

**Comment by dabeng** [comment]
Hi @Laurianti , if the center point of wrapper is located in the blank space, the chart with enabled "pan" option will easily disappear when users zoom in/out.

**Comment by Laurianti** [comment]
There was a bug.
https://jsfiddle.net/uhoekk0v/2/

**Comment by dabeng** [comment]
Hi @Laurianti , thanks a lot for your awesome online demo, but I still believe it's most reasonable to treat  the center point of the chart as the transform-origin.
