### ISSUE TITLE
Export Issue with Huge chart & Zoom feature

### ISSUE THREAD

**Issue by Mmannem** [dabeng/OrgChart#94]
@dabeng Export working only with visible part of the chart container, if we enable Zoom feature.
Can't we get full chart (whatever is on Chart container ) even if we enable options
'pan': true,
'zoom': true
Any work around for this ?

**Comment by dabeng** [comment]
Hi @Mmannem , I tested the use case you mentioned above on Chrome or Firefox, but I couldn't come across the bug. Maybe you should proved a online demo with bug.
