### ISSUE TITLE
Add search to chart 

### ISSUE THREAD

**Issue by ehsanmohammadi72** [dabeng/OrgChart#95]
hi @dabeng , in this demo [http://dabeng.github.io/OrgChart/filter-node/](http://dabeng.github.io/OrgChart/filter-node/) when only root node is visible and search a child node inside the chart ,the root node will be shown only!  is very good to expand the chart and show that node.something like this [http://bl.ocks.org/jjzieve/a743242f46321491a950](http://bl.ocks.org/jjzieve/a743242f46321491a950) . select2 library [https://select2.github.io/](https://select2.github.io/) is very nice for this .

**Comment by dabeng** [comment]
Hi @ehsanmohammadi72 , I'll take the time to fix the bug you mentioned above, but I'm not going to introduce the select2 library into orgchart plugin because I think it will make a fuss.
