### ISSUE TITLE
problem with cancel button in Filter 

### ISSUE THREAD

**Issue by ehsanmohammadi72** [dabeng/OrgChart#97]
Hi @dabeng , Tnx for add search that i want :)
now base in  http://dabeng.github.io/OrgChart/filter-node/ when i open my chart only root and 1 depth of child is visible .
after i search in my chart and click to cancel button all the node shown !
my chart is huge and i want when i click to cancel button only 1 depth of child show just like i open my chart .
TNX for help !

**Comment by dabeng** [comment]
Sorry @ehsanmohammadi72 , your demand is too deep customized, I think you should finish it by yourself.
