### ISSUE TITLE
How do I add more content to the nodes

### ISSUE THREAD

**Issue by srsshetty** [dabeng/OrgChart#98]
currently the standard is one content like for eg title. I want to be able to add more content and with a label. is it possible ?

**Comment by achristmann** [comment]
Yes, with the 'createNode': function ($node, $data) {} option.  $node will be a jquery object referencing the node, and you can then operate on it normally.  For example:

'createNode: function($node, $data) {
                    $('<image src="' + $data.image + '" />')
                        .appendTo($('<div class="content"></div>')
                            .insertAfter($node.find('.title')));
}
