### ISSUE TITLE
Vertical line in hybrid mode

### ISSUE THREAD

**Issue by tedliang** [dabeng/OrgChart#99]
Attempt to show vertical line in hybrid mode.
Please see https://jsfiddle.net/TedLiang/4rsagd4e/7/
Related to #61

**Comment by dabeng** [comment]
Wow! Awesome! I'm glad to introduce this demo into the readme page so that more people could be inspired by your code snippets. :blush:

**Comment by WHATTHEBEET** [comment]
Ohhhhh! Awesome!
